// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  email: {
    layout: {
      /**
       * Q​O​O​M​B
       */
      brand: string;
      /**
       * I​f​ ​t​h​e​ ​b​u​t​t​o​n​ ​d​o​e​s​n​'​t​ ​w​o​r​k​,​ ​c​o​p​y​ ​t​h​i​s​ ​l​i​n​k​ ​i​n​t​o​ ​y​o​u​r​ ​b​r​o​w​s​e​r​:
       */
      fallbackLinkLabel: string;
      /**
       * Y​o​u​ ​r​e​c​e​i​v​e​d​ ​t​h​i​s​ ​e​m​a​i​l​ ​b​e​c​a​u​s​e​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​i​s​ ​r​e​g​i​s​t​e​r​e​d​ ​o​n​ ​Q​o​o​m​b​.
       */
      unsubscribeNote: string;
    };
    emailVerification: {
      /**
       * V​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​–​ ​Q​o​o​m​b
       */
      subject: string;
      /**
       * V​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l
       */
      title: string;
      /**
       * H​e​l​l​o​,
       */
      greeting: string;
      /**
       * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​o​ ​a​c​t​i​v​a​t​e​ ​y​o​u​r​ ​Q​o​o​m​b​ ​a​c​c​o​u​n​t​.
       */
      body: string;
      /**
       * T​h​e​ ​l​i​n​k​ ​i​s​ ​v​a​l​i​d​ ​f​o​r​ ​<​s​t​r​o​n​g​>​2​4​ ​h​o​u​r​s​<​/​s​t​r​o​n​g​>​.
       */
      validity: string;
      /**
       * V​e​r​i​f​y​ ​e​m​a​i​l
       */
      cta: string;
      /**
       * I​f​ ​y​o​u​ ​d​i​d​ ​n​o​t​ ​c​r​e​a​t​e​ ​a​ ​Q​o​o​m​b​ ​a​c​c​o​u​n​t​,​ ​p​l​e​a​s​e​ ​i​g​n​o​r​e​ ​t​h​i​s​ ​e​m​a​i​l​.
       */
      footer: string;
    };
    passwordReset: {
      /**
       * R​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​–​ ​Q​o​o​m​b
       */
      subject: string;
      /**
       * R​e​s​e​t​ ​y​o​u​r​ ​p​a​s​s​w​o​r​d
       */
      title: string;
      /**
       * H​e​l​l​o​,
       */
      greeting: string;
      /**
       * Y​o​u​ ​r​e​q​u​e​s​t​e​d​ ​a​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​ ​f​o​r​ ​y​o​u​r​ ​Q​o​o​m​b​ ​a​c​c​o​u​n​t​.
       */
      body: string;
      /**
       * T​h​e​ ​l​i​n​k​ ​i​s​ ​v​a​l​i​d​ ​f​o​r​ ​<​s​t​r​o​n​g​>​1​ ​h​o​u​r​<​/​s​t​r​o​n​g​>​.
       */
      validity: string;
      /**
       * I​f​ ​y​o​u​ ​d​i​d​ ​n​o​t​ ​r​e​q​u​e​s​t​ ​a​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​,​ ​y​o​u​ ​c​a​n​ ​s​a​f​e​l​y​ ​i​g​n​o​r​e​ ​t​h​i​s​ ​e​m​a​i​l​.​ ​Y​o​u​r​ ​p​a​s​s​w​o​r​d​ ​w​i​l​l​ ​r​e​m​a​i​n​ ​u​n​c​h​a​n​g​e​d​.
       */
      warning: string;
      /**
       * S​e​t​ ​n​e​w​ ​p​a​s​s​w​o​r​d
       */
      cta: string;
      /**
       * I​f​ ​y​o​u​ ​d​i​d​ ​n​o​t​ ​r​e​q​u​e​s​t​ ​a​ ​p​a​s​s​w​o​r​d​ ​r​e​s​e​t​,​ ​p​l​e​a​s​e​ ​i​g​n​o​r​e​ ​t​h​i​s​ ​e​m​a​i​l​.
       */
      footer: string;
    };
    invitation: {
      /**
       * {​{​s​t​r​i​n​g​}​}​ ​i​n​v​i​t​e​d​ ​y​o​u​ ​t​o​ ​Q​o​o​m​b
       */
      subject: string;
      /**
       * Y​o​u​'​v​e​ ​b​e​e​n​ ​i​n​v​i​t​e​d
       */
      title: string;
      /**
       * H​e​l​l​o​,
       */
      greeting: string;
      /**
       * <​s​t​r​o​n​g​>​{​{​s​t​r​i​n​g​}​}​<​/​s​t​r​o​n​g​>​ ​h​a​s​ ​i​n​v​i​t​e​d​ ​y​o​u​ ​t​o​ ​j​o​i​n​ ​<​s​t​r​o​n​g​>​Q​o​o​m​b​<​/​s​t​r​o​n​g​>​ ​—​ ​t​h​e​ ​p​r​i​v​a​t​e​ ​o​r​g​a​n​i​z​a​t​i​o​n​ ​p​l​a​t​f​o​r​m​ ​f​o​r​ ​f​a​m​i​l​i​e​s​ ​a​n​d​ ​t​e​a​m​s​.
       */
      body: string;
      /**
       * T​h​e​ ​i​n​v​i​t​a​t​i​o​n​ ​i​s​ ​v​a​l​i​d​ ​f​o​r​ ​<​s​t​r​o​n​g​>​7​ ​d​a​y​s​<​/​s​t​r​o​n​g​>​.
       */
      validity: string;
      /**
       * A​c​c​e​p​t​ ​i​n​v​i​t​a​t​i​o​n
       */
      cta: string;
      /**
       * I​f​ ​y​o​u​ ​d​i​d​ ​n​o​t​ ​e​x​p​e​c​t​ ​t​h​i​s​ ​i​n​v​i​t​a​t​i​o​n​,​ ​p​l​e​a​s​e​ ​i​g​n​o​r​e​ ​t​h​i​s​ ​e​m​a​i​l​.
       */
      footer: string;
    };
  };
};

export type TranslationFunctions = {
  email: {
    layout: {
      /**
       * QOOMB
       */
      brand: () => LocalizedString;
      /**
       * If the button doesn't work, copy this link into your browser:
       */
      fallbackLinkLabel: () => LocalizedString;
      /**
       * You received this email because your account is registered on Qoomb.
       */
      unsubscribeNote: () => LocalizedString;
    };
    emailVerification: {
      /**
       * Verify your email address – Qoomb
       */
      subject: () => LocalizedString;
      /**
       * Verify your email
       */
      title: () => LocalizedString;
      /**
       * Hello,
       */
      greeting: () => LocalizedString;
      /**
       * Please verify your email address to activate your Qoomb account.
       */
      body: () => LocalizedString;
      /**
       * The link is valid for <strong>24 hours</strong>.
       */
      validity: () => LocalizedString;
      /**
       * Verify email
       */
      cta: () => LocalizedString;
      /**
       * If you did not create a Qoomb account, please ignore this email.
       */
      footer: () => LocalizedString;
    };
    passwordReset: {
      /**
       * Reset your password – Qoomb
       */
      subject: () => LocalizedString;
      /**
       * Reset your password
       */
      title: () => LocalizedString;
      /**
       * Hello,
       */
      greeting: () => LocalizedString;
      /**
       * You requested a password reset for your Qoomb account.
       */
      body: () => LocalizedString;
      /**
       * The link is valid for <strong>1 hour</strong>.
       */
      validity: () => LocalizedString;
      /**
       * If you did not request a password reset, you can safely ignore this email. Your password will remain unchanged.
       */
      warning: () => LocalizedString;
      /**
       * Set new password
       */
      cta: () => LocalizedString;
      /**
       * If you did not request a password reset, please ignore this email.
       */
      footer: () => LocalizedString;
    };
    invitation: {
      /**
       * {{string}} invited you to Qoomb
       */
      subject: (arg: { inviterName: number | string | boolean }) => LocalizedString;
      /**
       * You've been invited
       */
      title: () => LocalizedString;
      /**
       * Hello,
       */
      greeting: () => LocalizedString;
      /**
       * <strong>{{string}}</strong> has invited you to join <strong>Qoomb</strong> — the private organization platform for families and teams.
       */
      body: (arg: { inviterName: number | string | boolean }) => LocalizedString;
      /**
       * The invitation is valid for <strong>7 days</strong>.
       */
      validity: () => LocalizedString;
      /**
       * Accept invitation
       */
      cta: () => LocalizedString;
      /**
       * If you did not expect this invitation, please ignore this email.
       */
      footer: () => LocalizedString;
    };
  };
};

export type Formatters = {};
