// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'de-AT' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * Q​O​O​M​B
     */
    brand: string;
    /**
     * Y​o​u​r​ ​h​i​v​e​,​ ​o​r​g​a​n​i​s​e​d
     */
    tagline: string;
    /**
     * L​o​a​d​i​n​g​.​.​.
     */
    loading: string;
    /**
     * S​a​v​e
     */
    save: string;
    /**
     * S​a​v​i​n​g​.​.​.
     */
    saving: string;
    /**
     * C​a​n​c​e​l
     */
    cancel: string;
    /**
     * A​d​d
     */
    add: string;
    /**
     * R​e​m​o​v​e
     */
    remove: string;
    /**
     * B​a​c​k
     */
    back: string;
    /**
     * D​e​t​a​i​l​s
     */
    details: string;
    /**
     * S​h​o​w​ ​a​l​l
     */
    showAll: string;
    /**
     * o​r
     */
    or: string;
    /**
     * E​m​a​i​l
     */
    emailLabel: string;
    /**
     * P​a​s​s​w​o​r​d
     */
    passwordLabel: string;
    /**
     * M​i​n​.​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​w​i​t​h​ ​u​p​p​e​r​c​a​s​e​,​ ​n​u​m​b​e​r​ ​a​n​d​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
     */
    passwordHint: string;
    /**
     * C​r​e​a​t​e
     */
    create: string;
    /**
     * I​n​v​i​t​e
     */
    invite: string;
    /**
     * N​o​ ​r​e​s​u​l​t​s​ ​f​o​u​n​d​.
     */
    noResults: string;
  };
  nav: {
    /**
     * O​v​e​r​v​i​e​w
     */
    overview: string;
    /**
     * C​a​l​e​n​d​a​r
     */
    calendar: string;
    /**
     * L​i​s​t​s
     */
    lists: string;
    /**
     * M​e​m​b​e​r​s
     */
    members: string;
    /**
     * G​r​o​u​p​s
     */
    groups: string;
    /**
     * P​a​g​e​s
     */
    pages: string;
    /**
     * S​e​t​t​i​n​g​s
     */
    settings: string;
    /**
     * M​a​i​n​ ​n​a​v​i​g​a​t​i​o​n
     */
    mainLabel: string;
    /**
     * M​o​b​i​l​e​ ​n​a​v​i​g​a​t​i​o​n
     */
    mobileLabel: string;
  };
  entities: {
    /**
     * E​v​e​n​t
     */
    event: string;
    /**
     * L​i​s​t
     */
    list: string;
    /**
     * P​a​g​e
     */
    page: string;
  };
  roles: {
    /**
     * P​a​r​e​n​t
     */
    parent: string;
    /**
     * C​h​i​l​d
     */
    child: string;
    /**
     * G​u​e​s​t
     */
    guest: string;
    /**
     * A​d​m​i​n
     */
    orgAdmin: string;
    /**
     * M​a​n​a​g​e​r
     */
    manager: string;
    /**
     * M​e​m​b​e​r
     */
    member: string;
  };
  auth: {
    /**
     * S​i​g​n​ ​i​n
     */
    signIn: string;
    /**
     * B​a​c​k​ ​t​o​ ​s​i​g​n​ ​i​n
     */
    backToSignIn: string;
    login: {
      /**
       * W​e​l​c​o​m​e​ ​b​a​c​k
       */
      title: string;
      /**
       * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​h​i​v​e
       */
      subtitle: string;
      /**
       * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
       */
      forgotPassword: string;
      /**
       * N​o​ ​a​c​c​o​u​n​t​?
       */
      noAccount: string;
      /**
       * C​r​e​a​t​e​ ​o​n​e
       */
      createOne: string;
    };
    register: {
      /**
       * C​r​e​a​t​e​ ​y​o​u​r​ ​h​i​v​e
       */
      title: string;
      /**
       * A​c​c​e​p​t​ ​i​n​v​i​t​a​t​i​o​n
       */
      titleInvite: string;
      /**
       * S​e​t​ ​u​p​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​t​o​ ​j​o​i​n​ ​t​h​e​ ​h​i​v​e
       */
      subtitleInvite: string;
      /**
       * S​t​a​r​t​ ​o​r​g​a​n​i​s​i​n​g​ ​y​o​u​r​ ​f​a​m​i​l​y​ ​o​r​ ​t​e​a​m
       */
      subtitle: string;
      /**
       * Y​o​u​r​ ​n​a​m​e
       */
      nameLabel: string;
      /**
       * H​i​v​e​ ​n​a​m​e
       */
      hiveNameLabel: string;
      /**
       * e​.​g​.​ ​D​o​e​ ​F​a​m​i​l​y
       */
      hiveNamePlaceholder: string;
      /**
       * H​i​v​e​ ​t​y​p​e
       */
      hiveTypeLabel: string;
      /**
       * J​o​i​n​ ​h​i​v​e
       */
      joinHive: string;
      /**
       * C​r​e​a​t​e​ ​h​i​v​e
       */
      createHive: string;
      /**
       * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
       */
      alreadyHaveAccount: string;
    };
    forgotPassword: {
      /**
       * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d
       */
      title: string;
      /**
       * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​n​d​ ​w​e​'​l​l​ ​s​e​n​d​ ​y​o​u​ ​a​ ​r​e​s​e​t​ ​l​i​n​k
       */
      subtitle: string;
      /**
       * S​e​n​d​ ​r​e​s​e​t​ ​l​i​n​k
       */
      sendResetLink: string;
      /**
       * C​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l
       */
      successTitle: string;
      /**
       * I​f​ ​a​n​ ​a​c​c​o​u​n​t​ ​e​x​i​s​t​s​ ​f​o​r​ ​t​h​a​t​ ​a​d​d​r​e​s​s​,​ ​w​e​ ​s​e​n​t​ ​a​ ​r​e​s​e​t​ ​l​i​n​k​.​ ​I​t​ ​e​x​p​i​r​e​s​ ​i​n​ ​1​ ​h​o​u​r​.
       */
      successSubtitle: string;
    };
    resetPassword: {
      /**
       * R​e​s​e​t​ ​p​a​s​s​w​o​r​d
       */
      title: string;
      /**
       * C​h​o​o​s​e​ ​a​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​y​o​u​r​ ​a​c​c​o​u​n​t
       */
      subtitle: string;
      /**
       * N​e​w​ ​p​a​s​s​w​o​r​d
       */
      newPasswordLabel: string;
      /**
       * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
       */
      confirmPasswordLabel: string;
      /**
       * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h​.
       */
      passwordMismatch: string;
      /**
       * S​e​t​ ​n​e​w​ ​p​a​s​s​w​o​r​d
       */
      setNewPassword: string;
    };
    verifyEmail: {
      /**
       * V​e​r​i​f​y​i​n​g​ ​y​o​u​r​ ​e​m​a​i​l​…
       */
      loadingTitle: string;
      /**
       * E​m​a​i​l​ ​v​e​r​i​f​i​e​d
       */
      successTitle: string;
      /**
       * Y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​h​a​s​ ​b​e​e​n​ ​c​o​n​f​i​r​m​e​d​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​u​s​e​ ​a​l​l​ ​f​e​a​t​u​r​e​s​.
       */
      successSubtitle: string;
      /**
       * G​o​ ​t​o​ ​d​a​s​h​b​o​a​r​d
       */
      goToDashboard: string;
      /**
       * V​e​r​i​f​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
       */
      failedTitle: string;
      /**
       * T​h​i​s​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​h​a​s​ ​e​x​p​i​r​e​d​.
       */
      failedSubtitle: string;
    };
    passKey: {
      /**
       * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​P​a​s​s​K​e​y
       */
      signInWithPassKey: string;
      /**
       * P​a​s​s​K​e​y​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
       */
      authFailed: string;
      /**
       * R​e​g​i​s​t​r​a​t​i​o​n​ ​f​a​i​l​e​d
       */
      registrationFailed: string;
      /**
       * P​a​s​s​K​e​y​s
       */
      sectionTitle: string;
      /**
       * A​d​d​ ​P​a​s​s​K​e​y
       */
      addPassKey: string;
      /**
       * D​e​v​i​c​e​ ​n​a​m​e​ ​(​o​p​t​i​o​n​a​l​)
       */
      deviceNamePlaceholder: string;
      /**
       * R​e​g​i​s​t​e​r​ ​P​a​s​s​K​e​y
       */
      registerPassKey: string;
      /**
       * N​o​ ​P​a​s​s​K​e​y​s​ ​r​e​g​i​s​t​e​r​e​d​ ​y​e​t​.
       */
      noPassKeysYet: string;
      /**
       * P​a​s​s​K​e​y
       */
      defaultName: string;
      /**
       * A​d​d​e​d
       */
      added: string;
      /**
       * L​a​s​t​ ​u​s​e​d
       */
      lastUsed: string;
      /**
       * N​e​v​e​r
       */
      never: string;
    };
  };
  layout: {
    emailVerification: {
      /**
       * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​o​ ​u​n​l​o​c​k​ ​a​l​l​ ​f​e​a​t​u​r​e​s​.
       */
      message: string;
      /**
       * E​m​a​i​l​ ​s​e​n​t​ ​✓
       */
      sent: string;
      /**
       * R​e​s​e​n​d
       */
      resend: string;
      /**
       * D​i​s​m​i​s​s
       */
      dismiss: string;
    };
    hiveSwitcher: {
      /**
       * S​e​l​e​c​t​ ​h​i​v​e
       */
      selectHive: string;
    };
    userMenu: {
      /**
       * P​r​o​f​i​l​e
       */
      profile: string;
      /**
       * S​i​g​n​ ​o​u​t
       */
      logout: string;
    };
  };
  profile: {
    /**
     * P​r​o​f​i​l​e
     */
    title: string;
    /**
     * D​i​s​p​l​a​y​ ​n​a​m​e
     */
    displayNameLabel: string;
    /**
     * Y​o​u​r​ ​n​a​m​e
     */
    displayNamePlaceholder: string;
    /**
     * E​m​a​i​l
     */
    emailLabel: string;
    /**
     * R​o​l​e
     */
    roleLabel: string;
    /**
     * B​i​r​t​h​d​a​y
     */
    birthdayLabel: string;
    /**
     * P​r​o​f​i​l​e​ ​s​a​v​e​d​!
     */
    saved: string;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    saveError: string;
    language: {
      /**
       * L​a​n​g​u​a​g​e
       */
      title: string;
      /**
       * C​h​o​o​s​e​ ​t​h​e​ ​l​a​n​g​u​a​g​e​ ​f​o​r​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e
       */
      description: string;
      /**
       * L​a​n​g​u​a​g​e​ ​u​p​d​a​t​e​d​!
       */
      saved: string;
      /**
       * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​l​a​n​g​u​a​g​e​.
       */
      saveError: string;
      /**
       * D​e​u​t​s​c​h​ ​(​D​e​u​t​s​c​h​l​a​n​d​)
       */
      deDE: string;
      /**
       * D​e​u​t​s​c​h​ ​(​Ö​s​t​e​r​r​e​i​c​h​)
       */
      deAT: string;
      /**
       * E​n​g​l​i​s​h​ ​(​U​S​)
       */
      enUS: string;
    };
    security: {
      /**
       * S​e​c​u​r​i​t​y
       */
      title: string;
      /**
       * M​a​n​a​g​e​ ​y​o​u​r​ ​P​a​s​s​K​e​y​s​ ​a​n​d​ ​l​o​g​i​n​ ​m​e​t​h​o​d​s
       */
      description: string;
    };
  };
  dashboard: {
    /**
     * {​c​o​u​n​t​}​ ​m​e​m​b​e​r​s
     * @param {number} count
     */
    memberCount: RequiredParams<'count'>;
    greetings: {
      /**
       * G​o​o​d​ ​m​o​r​n​i​n​g​,​ ​{​n​a​m​e​}​!​ ​☀​️
       * @param {string} name
       */
      morning0: RequiredParams<'name'>;
      /**
       * R​i​s​e​ ​a​n​d​ ​s​h​i​n​e​,​ ​{​n​a​m​e​}​!
       * @param {string} name
       */
      morning1: RequiredParams<'name'>;
      /**
       * M​o​r​n​i​n​g​,​ ​{​n​a​m​e​}​!​ ​☀​️
       * @param {string} name
       */
      morning2: RequiredParams<'name'>;
      /**
       * H​e​y​ ​{​n​a​m​e​}​,​ ​t​h​e​r​e​ ​y​o​u​ ​a​r​e​!
       * @param {string} name
       */
      afternoon0: RequiredParams<'name'>;
      /**
       * G​l​a​d​ ​y​o​u​'​r​e​ ​h​e​r​e​,​ ​{​n​a​m​e​}​!
       * @param {string} name
       */
      afternoon1: RequiredParams<'name'>;
      /**
       * W​e​l​c​o​m​e​ ​b​a​c​k​,​ ​{​n​a​m​e​}​!
       * @param {string} name
       */
      afternoon2: RequiredParams<'name'>;
      /**
       * G​o​o​d​ ​e​v​e​n​i​n​g​,​ ​{​n​a​m​e​}​!​ ​�​�
       * @param {string} name
       */
      evening0: RequiredParams<'name'>;
      /**
       * G​o​o​d​ ​t​o​ ​s​e​e​ ​y​o​u​,​ ​{​n​a​m​e​}​!​ ​�​�
       * @param {string} name
       */
      evening1: RequiredParams<'name'>;
      /**
       * T​i​m​e​ ​t​o​ ​u​n​w​i​n​d​,​ ​{​n​a​m​e​}​!​ ​�​�
       * @param {string} name
       */
      evening2: RequiredParams<'name'>;
      /**
       * S​t​i​l​l​ ​u​p​,​ ​{​n​a​m​e​}​?
       * @param {string} name
       */
      night0: RequiredParams<'name'>;
      /**
       * B​u​r​n​i​n​g​ ​t​h​e​ ​m​i​d​n​i​g​h​t​ ​o​i​l​,​ ​{​n​a​m​e​}​?​ ​�​�
       * @param {string} name
       */
      night1: RequiredParams<'name'>;
      /**
       * S​t​i​l​l​ ​g​o​i​n​g​ ​s​t​r​o​n​g​,​ ​{​n​a​m​e​}​!​ ​�​�
       * @param {string} name
       */
      night2: RequiredParams<'name'>;
    };
    /**
     * T​o​d​a​y​:​
     */
    todayIntro: string;
    /**
     * o​p​e​n
     */
    openLabel: string;
    /**
     * N​e​x​t​ ​e​v​e​n​t
     */
    nextEvent: string;
    /**
     * M​o​r​e​ ​e​v​e​n​t​s
     */
    moreEvents: string;
    /**
     * {​d​o​n​e​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​c​o​m​p​l​e​t​e​d
     * @param {number} done
     * @param {number} total
     */
    progressText: RequiredParams<'done' | 'total'>;
    /**
     * A​d​d​ ​i​t​e​m
     */
    addListItem: string;
    /**
     * N​o​ ​e​v​e​n​t​s​ ​p​l​a​n​n​e​d​ ​y​e​t​.
     */
    emptyEvents: string;
    /**
     * T​h​i​s​ ​l​i​s​t​ ​i​s​ ​e​m​p​t​y​.
     */
    emptyList: string;
    quickAdd: {
      /**
       * Q​u​i​c​k​ ​a​d​d
       */
      title: string;
      /**
       * W​h​a​t​'​s​ ​c​o​m​i​n​g​ ​u​p​ ​n​e​x​t​?
       */
      placeholder: string;
    };
  };
  members: {
    /**
     * M​e​m​b​e​r​s
     */
    title: string;
    /**
     * I​n​v​i​t​e​ ​m​e​m​b​e​r
     */
    invite: string;
    /**
     * E​m​a​i​l​ ​a​d​d​r​e​s​s
     */
    inviteEmailLabel: string;
    /**
     * n​a​m​e​@​e​x​a​m​p​l​e​.​c​o​m
     */
    inviteEmailPlaceholder: string;
    /**
     * S​e​n​d​ ​i​n​v​i​t​a​t​i​o​n
     */
    inviteSend: string;
    /**
     * I​n​v​i​t​a​t​i​o​n​ ​s​e​n​t​!
     */
    inviteSuccess: string;
    /**
     * C​h​a​n​g​e​ ​r​o​l​e
     */
    changeRole: string;
    /**
     * C​h​a​n​g​e​ ​{​n​a​m​e​}​'​s​ ​r​o​l​e​?
     * @param {string} name
     */
    changeRoleConfirm: RequiredParams<'name'>;
    /**
     * R​e​m​o​v​e​ ​m​e​m​b​e​r
     */
    removeMember: string;
    /**
     * R​e​m​o​v​e​ ​{​n​a​m​e​}​ ​f​r​o​m​ ​t​h​e​ ​h​i​v​e​?
     * @param {string} name
     */
    removeConfirm: RequiredParams<'name'>;
    /**
     * N​o​ ​m​e​m​b​e​r​s​ ​y​e​t​.
     */
    emptyState: string;
    /**
     * (​Y​o​u​)
     */
    you: string;
    /**
     * J​o​i​n​e​d
     */
    joined: string;
    /**
     * P​e​n​d​i​n​g​ ​I​n​v​i​t​a​t​i​o​n​s
     */
    pendingInvitations: string;
    /**
     * I​n​v​i​t​e​d
     */
    invitedAt: string;
    /**
     * E​x​p​i​r​e​s
     */
    expiresAt: string;
    /**
     * R​e​s​e​n​d
     */
    resendInvitation: string;
    /**
     * R​e​v​o​k​e
     */
    revokeInvitation: string;
    /**
     * R​e​v​o​k​e​ ​t​h​i​s​ ​i​n​v​i​t​a​t​i​o​n​?
     */
    revokeConfirm: string;
  };
  groups: {
    /**
     * G​r​o​u​p​s
     */
    title: string;
    /**
     * N​e​w​ ​g​r​o​u​p
     */
    newGroup: string;
    /**
     * C​r​e​a​t​e​ ​g​r​o​u​p
     */
    createGroup: string;
    /**
     * G​r​o​u​p​ ​n​a​m​e
     */
    groupNameLabel: string;
    /**
     * e​.​g​.​ ​P​r​o​j​e​c​t​ ​t​e​a​m
     */
    groupNamePlaceholder: string;
    /**
     * D​e​s​c​r​i​p​t​i​o​n
     */
    descriptionLabel: string;
    /**
     * W​h​a​t​ ​i​s​ ​t​h​i​s​ ​g​r​o​u​p​ ​f​o​r​?
     */
    descriptionPlaceholder: string;
    /**
     * D​e​l​e​t​e​ ​g​r​o​u​p
     */
    deleteGroup: string;
    /**
     * T​h​i​s​ ​g​r​o​u​p​ ​a​n​d​ ​a​l​l​ ​a​s​s​i​g​n​m​e​n​t​s​ ​w​i​l​l​ ​b​e​ ​d​e​l​e​t​e​d​.
     */
    deleteConfirm: string;
    /**
     * N​o​ ​g​r​o​u​p​s​ ​y​e​t​.
     */
    emptyState: string;
    /**
     * C​r​e​a​t​e​ ​a​ ​g​r​o​u​p​ ​t​o​ ​o​r​g​a​n​i​s​e​ ​m​e​m​b​e​r​s​.
     */
    emptyStateHint: string;
    /**
     * {​c​o​u​n​t​}​ ​m​e​m​b​e​r​s
     * @param {number} count
     */
    memberCount: RequiredParams<'count'>;
    /**
     * A​d​d​ ​m​e​m​b​e​r
     */
    addMember: string;
    /**
     * R​e​m​o​v​e​ ​f​r​o​m​ ​g​r​o​u​p
     */
    removeMember: string;
    /**
     * R​e​m​o​v​e​ ​{​n​a​m​e​}​ ​f​r​o​m​ ​t​h​i​s​ ​g​r​o​u​p​?
     * @param {string} name
     */
    removeMemberConfirm: RequiredParams<'name'>;
    /**
     * N​o​ ​m​e​m​b​e​r​s​ ​i​n​ ​t​h​i​s​ ​g​r​o​u​p​ ​y​e​t​.
     */
    noMembers: string;
    /**
     * S​e​l​e​c​t​ ​m​e​m​b​e​r
     */
    selectMember: string;
    /**
     * B​a​c​k​ ​t​o​ ​g​r​o​u​p​s
     */
    backToGroups: string;
    /**
     * G​r​o​u​p​ ​n​o​t​ ​f​o​u​n​d​.
     */
    notFound: string;
  };
  lists: {
    /**
     * L​i​s​t​s
     */
    title: string;
    /**
     * N​e​w​ ​l​i​s​t
     */
    newList: string;
    /**
     * C​r​e​a​t​e​ ​l​i​s​t
     */
    createList: string;
    /**
     * N​a​m​e
     */
    listNameLabel: string;
    /**
     * e​.​g​.​ ​S​h​o​p​p​i​n​g​ ​l​i​s​t
     */
    listNamePlaceholder: string;
    /**
     * L​i​s​t​ ​c​r​e​a​t​e​d
     */
    createSuccess: string;
    /**
     * D​e​l​e​t​e​ ​l​i​s​t
     */
    deleteList: string;
    /**
     * T​h​i​s​ ​l​i​s​t​ ​a​n​d​ ​a​l​l​ ​i​t​s​ ​i​t​e​m​s​ ​w​i​l​l​ ​b​e​ ​p​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​d​.
     */
    deleteConfirm: string;
    /**
     * N​o​ ​l​i​s​t​s​ ​y​e​t​.
     */
    emptyState: string;
    /**
     * C​r​e​a​t​e​ ​a​ ​l​i​s​t​ ​t​o​ ​g​e​t​ ​s​t​a​r​t​e​d​.
     */
    emptyStateHint: string;
    /**
     * A​r​c​h​i​v​e​d
     */
    archivedBadge: string;
    /**
     * {​c​o​u​n​t​}​ ​i​t​e​m​s
     * @param {number} count
     */
    itemCount: RequiredParams<'count'>;
    /**
     * A​d​d​ ​i​t​e​m
     */
    addItem: string;
    /**
     * T​h​i​s​ ​l​i​s​t​ ​i​s​ ​e​m​p​t​y​.
     */
    emptyItems: string;
    /**
     * N​e​w​ ​i​t​e​m​…
     */
    itemNamePlaceholder: string;
    /**
     * B​a​c​k​ ​t​o​ ​l​i​s​t​s
     */
    backToLists: string;
    /**
     * L​i​s​t​ ​n​o​t​ ​f​o​u​n​d​.
     */
    notFound: string;
    /**
     * D​e​l​e​t​e​ ​i​t​e​m
     */
    deleteItem: string;
    /**
     * D​e​l​e​t​e​ ​t​h​i​s​ ​i​t​e​m​?
     */
    deleteItemConfirm: string;
    /**
     * A​d​d​ ​a​ ​f​i​e​l​d​ ​t​o​ ​s​t​a​r​t​ ​t​r​a​c​k​i​n​g​ ​d​a​t​a​.
     */
    noFields: string;
    /**
     * A​d​d​ ​f​i​e​l​d
     */
    addField: string;
    /**
     * F​i​e​l​d​ ​n​a​m​e
     */
    fieldNameLabel: string;
    /**
     * e​.​g​.​ ​S​t​a​t​u​s
     */
    fieldNamePlaceholder: string;
    /**
     * T​y​p​e
     */
    fieldTypeLabel: string;
    fieldTypes: {
      /**
       * T​e​x​t
       */
      text: string;
      /**
       * N​u​m​b​e​r
       */
      number: string;
      /**
       * D​a​t​e
       */
      date: string;
      /**
       * C​h​e​c​k​b​o​x
       */
      checkbox: string;
      /**
       * S​e​l​e​c​t
       */
      select: string;
      /**
       * U​R​L
       */
      url: string;
      /**
       * P​e​r​s​o​n
       */
      person: string;
      /**
       * R​e​f​e​r​e​n​c​e
       */
      reference: string;
    };
    /**
     * R​e​n​a​m​e​ ​l​i​s​t
     */
    editName: string;
    /**
     * C​h​a​n​g​e​ ​i​c​o​n
     */
    editIcon: string;
    /**
     * R​e​m​o​v​e​ ​f​i​e​l​d
     */
    removeField: string;
    /**
     * R​e​m​o​v​e​ ​t​h​i​s​ ​f​i​e​l​d​ ​a​n​d​ ​a​l​l​ ​i​t​s​ ​d​a​t​a​?
     */
    removeFieldConfirm: string;
    /**
     * F​r​o​m​ ​t​e​m​p​l​a​t​e
     */
    fromTemplate: string;
    /**
     * B​l​a​n​k​ ​l​i​s​t
     */
    blankList: string;
    /**
     * C​h​o​o​s​e​ ​a​ ​t​e​m​p​l​a​t​e
     */
    chooseTemplate: string;
    /**
     * A​r​c​h​i​v​e​ ​l​i​s​t
     */
    archive: string;
    /**
     * U​n​a​r​c​h​i​v​e​ ​l​i​s​t
     */
    unarchive: string;
    /**
     * T​h​i​s​ ​l​i​s​t​ ​i​s​ ​a​r​c​h​i​v​e​d​.
     */
    archivedNotice: string;
    /**
     * S​h​o​w​ ​a​r​c​h​i​v​e​d
     */
    showArchived: string;
    /**
     * H​i​d​e​ ​a​r​c​h​i​v​e​d
     */
    hideArchived: string;
    /**
     * S​e​t​t​i​n​g​s
     */
    settings: string;
    /**
     * V​i​s​i​b​i​l​i​t​y
     */
    visibilityLabel: string;
    visibility: {
      /**
       * H​i​v​e​ ​(​a​l​l​ ​m​e​m​b​e​r​s​)
       */
      hive: string;
      /**
       * A​d​m​i​n​s​ ​o​n​l​y
       */
      admins: string;
      /**
       * G​r​o​u​p
       */
      group: string;
      /**
       * P​r​i​v​a​t​e​ ​(​o​n​l​y​ ​m​e​)
       */
      private: string;
    };
    /**
     * G​r​o​u​p
     */
    groupLabel: string;
    /**
     * S​e​l​e​c​t​ ​a​ ​g​r​o​u​p
     */
    selectGroup: string;
    /**
     * R​e​n​a​m​e​ ​f​i​e​l​d
     */
    renameField: string;
    /**
     * C​o​n​f​i​g​u​r​e​ ​f​i​e​l​d
     */
    fieldConfig: string;
    /**
     * S​e​l​e​c​t​ ​o​p​t​i​o​n​s
     */
    selectOptions: string;
    /**
     * A​d​d​ ​o​p​t​i​o​n
     */
    addOption: string;
    /**
     * N​e​w​ ​o​p​t​i​o​n​…
     */
    optionPlaceholder: string;
    /**
     * S​a​v​e​ ​f​i​e​l​d
     */
    saveField: string;
    /**
     * S​a​v​e​d
     */
    updateSuccess: string;
    /**
     * E​r​r​o​r​ ​s​a​v​i​n​g
     */
    updateError: string;
    /**
     * E​r​r​o​r​ ​d​e​l​e​t​i​n​g
     */
    deleteError: string;
    /**
     * E​r​r​o​r​ ​c​r​e​a​t​i​n​g
     */
    createError: string;
    /**
     * F​i​e​l​d​ ​s​a​v​e​d
     */
    fieldSaved: string;
    /**
     * S​e​l​e​c​t​…
     */
    selectPlaceholder: string;
    /**
     * N​o​ ​o​p​t​i​o​n​s​ ​a​v​a​i​l​a​b​l​e
     */
    noOptions: string;
    /**
     * V​i​e​w​s
     */
    viewsLabel: string;
    /**
     * A​d​d​ ​v​i​e​w
     */
    addView: string;
    viewType: {
      /**
       * T​a​b​l​e
       */
      table: string;
      /**
       * C​h​e​c​k​l​i​s​t
       */
      checklist: string;
      /**
       * K​a​n​b​a​n
       */
      kanban: string;
    };
    /**
     * V​i​e​w​ ​n​a​m​e
     */
    newViewName: string;
    /**
     * N​o​ ​c​h​e​c​k​b​o​x​ ​f​i​e​l​d​ ​a​v​a​i​l​a​b​l​e​.​ ​A​d​d​ ​a​ ​c​h​e​c​k​b​o​x​ ​f​i​e​l​d​ ​f​i​r​s​t​.
     */
    noCheckboxField: string;
    /**
     * A​d​d​ ​c​h​e​c​k​b​o​x​ ​f​i​e​l​d
     */
    addCheckboxField: string;
    /**
     * D​o​n​e
     */
    checkboxFieldDefaultName: string;
    /**
     * D​o​n​e​ ​f​i​e​l​d
     */
    checkboxFieldLabel: string;
    /**
     * H​i​d​e​ ​d​o​n​e
     */
    hideDone: string;
    /**
     * S​h​o​w​ ​d​o​n​e
     */
    showDone: string;
    /**
     * A​l​l​ ​i​t​e​m​s​ ​d​o​n​e​ ​�​�
     */
    noUncheckedItems: string;
    /**
     * C​h​e​c​k​ ​a​l​l
     */
    checkAll: string;
    /**
     * D​e​l​e​t​e​ ​v​i​e​w
     */
    deleteView: string;
    /**
     * R​e​a​l​l​y​ ​d​e​l​e​t​e​ ​v​i​e​w​ ​"​{​n​a​m​e​}​"​?
     * @param {unknown} name
     */
    deleteViewConfirm: RequiredParams<'name'>;
    /**
     * D​u​p​l​i​c​a​t​e​ ​v​i​e​w
     */
    duplicateView: string;
    /**
     * (​C​o​p​y​)
     */
    duplicateViewSuffix: string;
    /**
     * R​e​n​a​m​e​ ​v​i​e​w
     */
    renameView: string;
    /**
     * V​i​e​w​ ​d​e​l​e​t​e​d
     */
    viewDeleted: string;
    /**
     * V​i​e​w​ ​r​e​n​a​m​e​d
     */
    viewRenamed: string;
    /**
     * V​i​e​w​ ​u​p​d​a​t​e​d
     */
    viewUpdated: string;
    /**
     * T​h​e​ ​l​a​s​t​ ​v​i​e​w​ ​c​a​n​n​o​t​ ​b​e​ ​d​e​l​e​t​e​d​.
     */
    lastViewWarning: string;
    /**
     * G​r​o​u​p​ ​b​y
     */
    kanbanGroupBy: string;
    /**
     * (​N​o​ ​v​a​l​u​e​)
     */
    kanbanNoValue: string;
    /**
     * N​o​ ​s​e​l​e​c​t​ ​f​i​e​l​d​ ​f​o​u​n​d​.​ ​P​l​e​a​s​e​ ​c​r​e​a​t​e​ ​a​ ​s​e​l​e​c​t​ ​f​i​e​l​d​ ​f​i​r​s​t​.
     */
    noSelectFields: string;
    /**
     * R​e​p​e​a​t​s
     */
    recurrenceLabel: string;
    /**
     * D​o​e​s​ ​n​o​t​ ​r​e​p​e​a​t
     */
    recurrenceNone: string;
    recurrenceFrequency: {
      /**
       * D​a​i​l​y
       */
      daily: string;
      /**
       * W​e​e​k​l​y
       */
      weekly: string;
      /**
       * M​o​n​t​h​l​y
       */
      monthly: string;
      /**
       * Y​e​a​r​l​y
       */
      yearly: string;
    };
    /**
     * E​v​e​r​y​ ​{​n​}​ ​…
     * @param {unknown} n
     */
    recurrenceInterval: RequiredParams<'n'>;
    /**
     * R​e​c​u​r​r​e​n​c​e​ ​s​a​v​e​d
     */
    recurrenceSaved: string;
    /**
     * S​e​a​r​c​h​ ​l​i​s​t​s​…
     */
    searchPlaceholder: string;
    /**
     * F​a​v​o​r​i​t​e​s
     */
    favorites: string;
    /**
     * N​o​ ​f​a​v​o​r​i​t​e​s​ ​y​e​t​.​ ​C​l​i​c​k​ ​t​h​e​ ​s​t​a​r​ ​n​e​x​t​ ​t​o​ ​a​ ​l​i​s​t​.
     */
    noFavorites: string;
    /**
     * A​d​d​e​d​ ​t​o​ ​f​a​v​o​r​i​t​e​s
     */
    favoriteAdded: string;
    /**
     * R​e​m​o​v​e​d​ ​f​r​o​m​ ​f​a​v​o​r​i​t​e​s
     */
    favoriteRemoved: string;
    /**
     * A​l​l​ ​l​i​s​t​s
     */
    allLists: string;
    /**
     * D​r​a​g​ ​t​o​ ​r​e​o​r​d​e​r
     */
    dragToReorder: string;
    /**
     * R​e​m​o​v​e​ ​f​r​o​m​ ​f​a​v​o​r​i​t​e​s
     */
    removeFromFavorites: string;
    /**
     * A​d​d​ ​t​o​ ​f​a​v​o​r​i​t​e​s
     */
    addToFavorites: string;
    /**
     * S​e​a​r​c​h​ ​f​o​r​ ​a​ ​p​e​r​s​o​n​…
     */
    personSearch: string;
    /**
     * S​e​a​r​c​h​ ​f​o​r​ ​a​ ​p​e​r​s​o​n
     */
    personSearchLabel: string;
    /**
     * S​e​l​e​c​t​ ​p​e​r​s​o​n​s
     */
    personPickerLabel: string;
    /**
     * R​e​m​o​v​e​ ​{​n​a​m​e​}
     * @param {unknown} name
     */
    personRemove: RequiredParams<'name'>;
    /**
     * N​o​t​ ​i​n​ ​s​y​s​t​e​m
     */
    personExternal: string;
    /**
     * A​d​d​ ​"​{​n​a​m​e​}​"
     * @param {unknown} name
     */
    personAddFreeText: RequiredParams<'name'>;
  };
  activity: {
    /**
     * A​c​t​i​v​i​t​y
     */
    title: string;
    /**
     * N​o​ ​r​e​c​e​n​t​ ​a​c​t​i​v​i​t​y​.
     */
    noActivity: string;
    /**
     * L​o​a​d​ ​m​o​r​e
     */
    loadMore: string;
  };
  notifications: {
    /**
     * N​o​t​i​f​i​c​a​t​i​o​n​s
     */
    title: string;
    /**
     * M​a​r​k​ ​a​l​l​ ​a​s​ ​r​e​a​d
     */
    markAllRead: string;
    /**
     * A​l​l
     */
    allNotifications: string;
    /**
     * U​n​r​e​a​d
     */
    onlyUnread: string;
    /**
     * N​o​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​ ​y​e​t​.
     */
    noNotifications: string;
    /**
     * M​a​r​k​ ​a​s​ ​r​e​a​d
     */
    markRead: string;
  };
  messaging: {
    /**
     * M​e​s​s​a​g​e​s
     */
    title: string;
    /**
     * N​o​ ​c​o​n​v​e​r​s​a​t​i​o​n​s​ ​y​e​t​.
     */
    noConversations: string;
    /**
     * N​o​ ​m​e​s​s​a​g​e​s​ ​y​e​t​.
     */
    noMessages: string;
    /**
     * S​e​l​e​c​t​ ​a​ ​c​o​n​v​e​r​s​a​t​i​o​n​ ​t​o​ ​s​t​a​r​t​ ​c​h​a​t​t​i​n​g​.
     */
    selectConversation: string;
    /**
     * W​r​i​t​e​ ​a​ ​m​e​s​s​a​g​e​…
     */
    messagePlaceholder: string;
    /**
     * S​e​n​d
     */
    send: string;
    /**
     * N​e​w​ ​m​e​s​s​a​g​e
     */
    newMessage: string;
    /**
     * {​c​o​u​n​t​}​ ​u​n​r​e​a​d
     * @param {number} count
     */
    unread: RequiredParams<'count'>;
  };
  hiveSettings: {
    /**
     * H​i​v​e​ ​S​e​t​t​i​n​g​s
     */
    title: string;
    /**
     * G​e​n​e​r​a​l
     */
    generalSection: string;
    /**
     * N​a​m​e
     */
    nameLabel: string;
    /**
     * Y​o​u​r​ ​h​i​v​e​ ​n​a​m​e
     */
    namePlaceholder: string;
    /**
     * L​a​n​g​u​a​g​e
     */
    localeLabel: string;
    /**
     * S​e​t​t​i​n​g​s​ ​s​a​v​e​d
     */
    saveSuccess: string;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e
     */
    saveError: string;
    /**
     * D​a​n​g​e​r​ ​Z​o​n​e
     */
    dangerZone: string;
    /**
     * P​e​r​m​a​n​e​n​t​l​y​ ​d​e​l​e​t​e​s​ ​t​h​e​ ​h​i​v​e​ ​a​n​d​ ​a​l​l​ ​i​t​s​ ​d​a​t​a​.​ ​T​h​i​s​ ​a​c​t​i​o​n​ ​c​a​n​n​o​t​ ​b​e​ ​u​n​d​o​n​e​.
     */
    deleteDescription: string;
    /**
     * T​y​p​e​ ​"​D​E​L​E​T​E​"​ ​t​o​ ​c​o​n​f​i​r​m
     */
    deleteConfirmLabel: string;
    /**
     * D​E​L​E​T​E
     */
    deleteConfirmPlaceholder: string;
    /**
     * D​e​l​e​t​e​ ​h​i​v​e
     */
    deleteButton: string;
    /**
     * N​o​t​i​f​i​c​a​t​i​o​n​s
     */
    notificationPrefsSection: string;
    /**
     * C​h​o​o​s​e​ ​w​h​i​c​h​ ​e​v​e​n​t​s​ ​t​r​i​g​g​e​r​ ​i​n​-​a​p​p​ ​a​n​d​ ​e​m​a​i​l​ ​n​o​t​i​f​i​c​a​t​i​o​n​s​.
     */
    notificationPrefsDescription: string;
    /**
     * I​n​-​A​p​p
     */
    notifInApp: string;
    /**
     * E​m​a​i​l
     */
    notifEmail: string;
    /**
     * P​r​e​f​e​r​e​n​c​e​s​ ​s​a​v​e​d
     */
    notifSaved: string;
    notifTypes: {
      /**
       * N​e​w​ ​m​e​m​b​e​r​ ​j​o​i​n​e​d
       */
      member_joined: string;
      /**
       * T​a​s​k​ ​a​s​s​i​g​n​e​d​ ​t​o​ ​m​e
       */
      task_assigned: string;
      /**
       * E​v​e​n​t​ ​r​e​m​i​n​d​e​r
       */
      event_reminder: string;
    };
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * QOOMB
     */
    brand: () => LocalizedString;
    /**
     * Your hive, organised
     */
    tagline: () => LocalizedString;
    /**
     * Loading...
     */
    loading: () => LocalizedString;
    /**
     * Save
     */
    save: () => LocalizedString;
    /**
     * Saving...
     */
    saving: () => LocalizedString;
    /**
     * Cancel
     */
    cancel: () => LocalizedString;
    /**
     * Add
     */
    add: () => LocalizedString;
    /**
     * Remove
     */
    remove: () => LocalizedString;
    /**
     * Back
     */
    back: () => LocalizedString;
    /**
     * Details
     */
    details: () => LocalizedString;
    /**
     * Show all
     */
    showAll: () => LocalizedString;
    /**
     * or
     */
    or: () => LocalizedString;
    /**
     * Email
     */
    emailLabel: () => LocalizedString;
    /**
     * Password
     */
    passwordLabel: () => LocalizedString;
    /**
     * Min. 8 characters with uppercase, number and special character
     */
    passwordHint: () => LocalizedString;
    /**
     * Create
     */
    create: () => LocalizedString;
    /**
     * Invite
     */
    invite: () => LocalizedString;
    /**
     * No results found.
     */
    noResults: () => LocalizedString;
  };
  nav: {
    /**
     * Overview
     */
    overview: () => LocalizedString;
    /**
     * Calendar
     */
    calendar: () => LocalizedString;
    /**
     * Lists
     */
    lists: () => LocalizedString;
    /**
     * Members
     */
    members: () => LocalizedString;
    /**
     * Groups
     */
    groups: () => LocalizedString;
    /**
     * Pages
     */
    pages: () => LocalizedString;
    /**
     * Settings
     */
    settings: () => LocalizedString;
    /**
     * Main navigation
     */
    mainLabel: () => LocalizedString;
    /**
     * Mobile navigation
     */
    mobileLabel: () => LocalizedString;
  };
  entities: {
    /**
     * Event
     */
    event: () => LocalizedString;
    /**
     * List
     */
    list: () => LocalizedString;
    /**
     * Page
     */
    page: () => LocalizedString;
  };
  roles: {
    /**
     * Parent
     */
    parent: () => LocalizedString;
    /**
     * Child
     */
    child: () => LocalizedString;
    /**
     * Guest
     */
    guest: () => LocalizedString;
    /**
     * Admin
     */
    orgAdmin: () => LocalizedString;
    /**
     * Manager
     */
    manager: () => LocalizedString;
    /**
     * Member
     */
    member: () => LocalizedString;
  };
  auth: {
    /**
     * Sign in
     */
    signIn: () => LocalizedString;
    /**
     * Back to sign in
     */
    backToSignIn: () => LocalizedString;
    login: {
      /**
       * Welcome back
       */
      title: () => LocalizedString;
      /**
       * Sign in to your hive
       */
      subtitle: () => LocalizedString;
      /**
       * Forgot password?
       */
      forgotPassword: () => LocalizedString;
      /**
       * No account?
       */
      noAccount: () => LocalizedString;
      /**
       * Create one
       */
      createOne: () => LocalizedString;
    };
    register: {
      /**
       * Create your hive
       */
      title: () => LocalizedString;
      /**
       * Accept invitation
       */
      titleInvite: () => LocalizedString;
      /**
       * Set up your account to join the hive
       */
      subtitleInvite: () => LocalizedString;
      /**
       * Start organising your family or team
       */
      subtitle: () => LocalizedString;
      /**
       * Your name
       */
      nameLabel: () => LocalizedString;
      /**
       * Hive name
       */
      hiveNameLabel: () => LocalizedString;
      /**
       * e.g. Doe Family
       */
      hiveNamePlaceholder: () => LocalizedString;
      /**
       * Hive type
       */
      hiveTypeLabel: () => LocalizedString;
      /**
       * Join hive
       */
      joinHive: () => LocalizedString;
      /**
       * Create hive
       */
      createHive: () => LocalizedString;
      /**
       * Already have an account?
       */
      alreadyHaveAccount: () => LocalizedString;
    };
    forgotPassword: {
      /**
       * Forgot password
       */
      title: () => LocalizedString;
      /**
       * Enter your email and we'll send you a reset link
       */
      subtitle: () => LocalizedString;
      /**
       * Send reset link
       */
      sendResetLink: () => LocalizedString;
      /**
       * Check your email
       */
      successTitle: () => LocalizedString;
      /**
       * If an account exists for that address, we sent a reset link. It expires in 1 hour.
       */
      successSubtitle: () => LocalizedString;
    };
    resetPassword: {
      /**
       * Reset password
       */
      title: () => LocalizedString;
      /**
       * Choose a new password for your account
       */
      subtitle: () => LocalizedString;
      /**
       * New password
       */
      newPasswordLabel: () => LocalizedString;
      /**
       * Confirm password
       */
      confirmPasswordLabel: () => LocalizedString;
      /**
       * Passwords do not match.
       */
      passwordMismatch: () => LocalizedString;
      /**
       * Set new password
       */
      setNewPassword: () => LocalizedString;
    };
    verifyEmail: {
      /**
       * Verifying your email…
       */
      loadingTitle: () => LocalizedString;
      /**
       * Email verified
       */
      successTitle: () => LocalizedString;
      /**
       * Your email address has been confirmed. You can now use all features.
       */
      successSubtitle: () => LocalizedString;
      /**
       * Go to dashboard
       */
      goToDashboard: () => LocalizedString;
      /**
       * Verification failed
       */
      failedTitle: () => LocalizedString;
      /**
       * This link is invalid or has expired.
       */
      failedSubtitle: () => LocalizedString;
    };
    passKey: {
      /**
       * Sign in with PassKey
       */
      signInWithPassKey: () => LocalizedString;
      /**
       * PassKey authentication failed
       */
      authFailed: () => LocalizedString;
      /**
       * Registration failed
       */
      registrationFailed: () => LocalizedString;
      /**
       * PassKeys
       */
      sectionTitle: () => LocalizedString;
      /**
       * Add PassKey
       */
      addPassKey: () => LocalizedString;
      /**
       * Device name (optional)
       */
      deviceNamePlaceholder: () => LocalizedString;
      /**
       * Register PassKey
       */
      registerPassKey: () => LocalizedString;
      /**
       * No PassKeys registered yet.
       */
      noPassKeysYet: () => LocalizedString;
      /**
       * PassKey
       */
      defaultName: () => LocalizedString;
      /**
       * Added
       */
      added: () => LocalizedString;
      /**
       * Last used
       */
      lastUsed: () => LocalizedString;
      /**
       * Never
       */
      never: () => LocalizedString;
    };
  };
  layout: {
    emailVerification: {
      /**
       * Please verify your email address to unlock all features.
       */
      message: () => LocalizedString;
      /**
       * Email sent ✓
       */
      sent: () => LocalizedString;
      /**
       * Resend
       */
      resend: () => LocalizedString;
      /**
       * Dismiss
       */
      dismiss: () => LocalizedString;
    };
    hiveSwitcher: {
      /**
       * Select hive
       */
      selectHive: () => LocalizedString;
    };
    userMenu: {
      /**
       * Profile
       */
      profile: () => LocalizedString;
      /**
       * Sign out
       */
      logout: () => LocalizedString;
    };
  };
  profile: {
    /**
     * Profile
     */
    title: () => LocalizedString;
    /**
     * Display name
     */
    displayNameLabel: () => LocalizedString;
    /**
     * Your name
     */
    displayNamePlaceholder: () => LocalizedString;
    /**
     * Email
     */
    emailLabel: () => LocalizedString;
    /**
     * Role
     */
    roleLabel: () => LocalizedString;
    /**
     * Birthday
     */
    birthdayLabel: () => LocalizedString;
    /**
     * Profile saved!
     */
    saved: () => LocalizedString;
    /**
     * Failed to save. Please try again.
     */
    saveError: () => LocalizedString;
    language: {
      /**
       * Language
       */
      title: () => LocalizedString;
      /**
       * Choose the language for the interface
       */
      description: () => LocalizedString;
      /**
       * Language updated!
       */
      saved: () => LocalizedString;
      /**
       * Failed to update language.
       */
      saveError: () => LocalizedString;
      /**
       * Deutsch (Deutschland)
       */
      deDE: () => LocalizedString;
      /**
       * Deutsch (Österreich)
       */
      deAT: () => LocalizedString;
      /**
       * English (US)
       */
      enUS: () => LocalizedString;
    };
    security: {
      /**
       * Security
       */
      title: () => LocalizedString;
      /**
       * Manage your PassKeys and login methods
       */
      description: () => LocalizedString;
    };
  };
  dashboard: {
    /**
     * {count} members
     */
    memberCount: (arg: { count: number }) => LocalizedString;
    greetings: {
      /**
       * Good morning, {name}! ☀️
       */
      morning0: (arg: { name: string }) => LocalizedString;
      /**
       * Rise and shine, {name}!
       */
      morning1: (arg: { name: string }) => LocalizedString;
      /**
       * Morning, {name}! ☀️
       */
      morning2: (arg: { name: string }) => LocalizedString;
      /**
       * Hey {name}, there you are!
       */
      afternoon0: (arg: { name: string }) => LocalizedString;
      /**
       * Glad you're here, {name}!
       */
      afternoon1: (arg: { name: string }) => LocalizedString;
      /**
       * Welcome back, {name}!
       */
      afternoon2: (arg: { name: string }) => LocalizedString;
      /**
       * Good evening, {name}! 🌆
       */
      evening0: (arg: { name: string }) => LocalizedString;
      /**
       * Good to see you, {name}! 🌆
       */
      evening1: (arg: { name: string }) => LocalizedString;
      /**
       * Time to unwind, {name}! 🌆
       */
      evening2: (arg: { name: string }) => LocalizedString;
      /**
       * Still up, {name}?
       */
      night0: (arg: { name: string }) => LocalizedString;
      /**
       * Burning the midnight oil, {name}? 🌙
       */
      night1: (arg: { name: string }) => LocalizedString;
      /**
       * Still going strong, {name}! 🌙
       */
      night2: (arg: { name: string }) => LocalizedString;
    };
    /**
     * Today:
     */
    todayIntro: () => LocalizedString;
    /**
     * open
     */
    openLabel: () => LocalizedString;
    /**
     * Next event
     */
    nextEvent: () => LocalizedString;
    /**
     * More events
     */
    moreEvents: () => LocalizedString;
    /**
     * {done} of {total} completed
     */
    progressText: (arg: { done: number; total: number }) => LocalizedString;
    /**
     * Add item
     */
    addListItem: () => LocalizedString;
    /**
     * No events planned yet.
     */
    emptyEvents: () => LocalizedString;
    /**
     * This list is empty.
     */
    emptyList: () => LocalizedString;
    quickAdd: {
      /**
       * Quick add
       */
      title: () => LocalizedString;
      /**
       * What's coming up next?
       */
      placeholder: () => LocalizedString;
    };
  };
  members: {
    /**
     * Members
     */
    title: () => LocalizedString;
    /**
     * Invite member
     */
    invite: () => LocalizedString;
    /**
     * Email address
     */
    inviteEmailLabel: () => LocalizedString;
    /**
     * name@example.com
     */
    inviteEmailPlaceholder: () => LocalizedString;
    /**
     * Send invitation
     */
    inviteSend: () => LocalizedString;
    /**
     * Invitation sent!
     */
    inviteSuccess: () => LocalizedString;
    /**
     * Change role
     */
    changeRole: () => LocalizedString;
    /**
     * Change {name}'s role?
     */
    changeRoleConfirm: (arg: { name: string }) => LocalizedString;
    /**
     * Remove member
     */
    removeMember: () => LocalizedString;
    /**
     * Remove {name} from the hive?
     */
    removeConfirm: (arg: { name: string }) => LocalizedString;
    /**
     * No members yet.
     */
    emptyState: () => LocalizedString;
    /**
     * (You)
     */
    you: () => LocalizedString;
    /**
     * Joined
     */
    joined: () => LocalizedString;
    /**
     * Pending Invitations
     */
    pendingInvitations: () => LocalizedString;
    /**
     * Invited
     */
    invitedAt: () => LocalizedString;
    /**
     * Expires
     */
    expiresAt: () => LocalizedString;
    /**
     * Resend
     */
    resendInvitation: () => LocalizedString;
    /**
     * Revoke
     */
    revokeInvitation: () => LocalizedString;
    /**
     * Revoke this invitation?
     */
    revokeConfirm: () => LocalizedString;
  };
  groups: {
    /**
     * Groups
     */
    title: () => LocalizedString;
    /**
     * New group
     */
    newGroup: () => LocalizedString;
    /**
     * Create group
     */
    createGroup: () => LocalizedString;
    /**
     * Group name
     */
    groupNameLabel: () => LocalizedString;
    /**
     * e.g. Project team
     */
    groupNamePlaceholder: () => LocalizedString;
    /**
     * Description
     */
    descriptionLabel: () => LocalizedString;
    /**
     * What is this group for?
     */
    descriptionPlaceholder: () => LocalizedString;
    /**
     * Delete group
     */
    deleteGroup: () => LocalizedString;
    /**
     * This group and all assignments will be deleted.
     */
    deleteConfirm: () => LocalizedString;
    /**
     * No groups yet.
     */
    emptyState: () => LocalizedString;
    /**
     * Create a group to organise members.
     */
    emptyStateHint: () => LocalizedString;
    /**
     * {count} members
     */
    memberCount: (arg: { count: number }) => LocalizedString;
    /**
     * Add member
     */
    addMember: () => LocalizedString;
    /**
     * Remove from group
     */
    removeMember: () => LocalizedString;
    /**
     * Remove {name} from this group?
     */
    removeMemberConfirm: (arg: { name: string }) => LocalizedString;
    /**
     * No members in this group yet.
     */
    noMembers: () => LocalizedString;
    /**
     * Select member
     */
    selectMember: () => LocalizedString;
    /**
     * Back to groups
     */
    backToGroups: () => LocalizedString;
    /**
     * Group not found.
     */
    notFound: () => LocalizedString;
  };
  lists: {
    /**
     * Lists
     */
    title: () => LocalizedString;
    /**
     * New list
     */
    newList: () => LocalizedString;
    /**
     * Create list
     */
    createList: () => LocalizedString;
    /**
     * Name
     */
    listNameLabel: () => LocalizedString;
    /**
     * e.g. Shopping list
     */
    listNamePlaceholder: () => LocalizedString;
    /**
     * List created
     */
    createSuccess: () => LocalizedString;
    /**
     * Delete list
     */
    deleteList: () => LocalizedString;
    /**
     * This list and all its items will be permanently deleted.
     */
    deleteConfirm: () => LocalizedString;
    /**
     * No lists yet.
     */
    emptyState: () => LocalizedString;
    /**
     * Create a list to get started.
     */
    emptyStateHint: () => LocalizedString;
    /**
     * Archived
     */
    archivedBadge: () => LocalizedString;
    /**
     * {count} items
     */
    itemCount: (arg: { count: number }) => LocalizedString;
    /**
     * Add item
     */
    addItem: () => LocalizedString;
    /**
     * This list is empty.
     */
    emptyItems: () => LocalizedString;
    /**
     * New item…
     */
    itemNamePlaceholder: () => LocalizedString;
    /**
     * Back to lists
     */
    backToLists: () => LocalizedString;
    /**
     * List not found.
     */
    notFound: () => LocalizedString;
    /**
     * Delete item
     */
    deleteItem: () => LocalizedString;
    /**
     * Delete this item?
     */
    deleteItemConfirm: () => LocalizedString;
    /**
     * Add a field to start tracking data.
     */
    noFields: () => LocalizedString;
    /**
     * Add field
     */
    addField: () => LocalizedString;
    /**
     * Field name
     */
    fieldNameLabel: () => LocalizedString;
    /**
     * e.g. Status
     */
    fieldNamePlaceholder: () => LocalizedString;
    /**
     * Type
     */
    fieldTypeLabel: () => LocalizedString;
    fieldTypes: {
      /**
       * Text
       */
      text: () => LocalizedString;
      /**
       * Number
       */
      number: () => LocalizedString;
      /**
       * Date
       */
      date: () => LocalizedString;
      /**
       * Checkbox
       */
      checkbox: () => LocalizedString;
      /**
       * Select
       */
      select: () => LocalizedString;
      /**
       * URL
       */
      url: () => LocalizedString;
      /**
       * Person
       */
      person: () => LocalizedString;
      /**
       * Reference
       */
      reference: () => LocalizedString;
    };
    /**
     * Rename list
     */
    editName: () => LocalizedString;
    /**
     * Change icon
     */
    editIcon: () => LocalizedString;
    /**
     * Remove field
     */
    removeField: () => LocalizedString;
    /**
     * Remove this field and all its data?
     */
    removeFieldConfirm: () => LocalizedString;
    /**
     * From template
     */
    fromTemplate: () => LocalizedString;
    /**
     * Blank list
     */
    blankList: () => LocalizedString;
    /**
     * Choose a template
     */
    chooseTemplate: () => LocalizedString;
    /**
     * Archive list
     */
    archive: () => LocalizedString;
    /**
     * Unarchive list
     */
    unarchive: () => LocalizedString;
    /**
     * This list is archived.
     */
    archivedNotice: () => LocalizedString;
    /**
     * Show archived
     */
    showArchived: () => LocalizedString;
    /**
     * Hide archived
     */
    hideArchived: () => LocalizedString;
    /**
     * Settings
     */
    settings: () => LocalizedString;
    /**
     * Visibility
     */
    visibilityLabel: () => LocalizedString;
    visibility: {
      /**
       * Hive (all members)
       */
      hive: () => LocalizedString;
      /**
       * Admins only
       */
      admins: () => LocalizedString;
      /**
       * Group
       */
      group: () => LocalizedString;
      /**
       * Private (only me)
       */
      private: () => LocalizedString;
    };
    /**
     * Group
     */
    groupLabel: () => LocalizedString;
    /**
     * Select a group
     */
    selectGroup: () => LocalizedString;
    /**
     * Rename field
     */
    renameField: () => LocalizedString;
    /**
     * Configure field
     */
    fieldConfig: () => LocalizedString;
    /**
     * Select options
     */
    selectOptions: () => LocalizedString;
    /**
     * Add option
     */
    addOption: () => LocalizedString;
    /**
     * New option…
     */
    optionPlaceholder: () => LocalizedString;
    /**
     * Save field
     */
    saveField: () => LocalizedString;
    /**
     * Saved
     */
    updateSuccess: () => LocalizedString;
    /**
     * Error saving
     */
    updateError: () => LocalizedString;
    /**
     * Error deleting
     */
    deleteError: () => LocalizedString;
    /**
     * Error creating
     */
    createError: () => LocalizedString;
    /**
     * Field saved
     */
    fieldSaved: () => LocalizedString;
    /**
     * Select…
     */
    selectPlaceholder: () => LocalizedString;
    /**
     * No options available
     */
    noOptions: () => LocalizedString;
    /**
     * Views
     */
    viewsLabel: () => LocalizedString;
    /**
     * Add view
     */
    addView: () => LocalizedString;
    viewType: {
      /**
       * Table
       */
      table: () => LocalizedString;
      /**
       * Checklist
       */
      checklist: () => LocalizedString;
      /**
       * Kanban
       */
      kanban: () => LocalizedString;
    };
    /**
     * View name
     */
    newViewName: () => LocalizedString;
    /**
     * No checkbox field available. Add a checkbox field first.
     */
    noCheckboxField: () => LocalizedString;
    /**
     * Add checkbox field
     */
    addCheckboxField: () => LocalizedString;
    /**
     * Done
     */
    checkboxFieldDefaultName: () => LocalizedString;
    /**
     * Done field
     */
    checkboxFieldLabel: () => LocalizedString;
    /**
     * Hide done
     */
    hideDone: () => LocalizedString;
    /**
     * Show done
     */
    showDone: () => LocalizedString;
    /**
     * All items done 🎉
     */
    noUncheckedItems: () => LocalizedString;
    /**
     * Check all
     */
    checkAll: () => LocalizedString;
    /**
     * Delete view
     */
    deleteView: () => LocalizedString;
    /**
     * Really delete view "{name}"?
     */
    deleteViewConfirm: (arg: { name: unknown }) => LocalizedString;
    /**
     * Duplicate view
     */
    duplicateView: () => LocalizedString;
    /**
     * (Copy)
     */
    duplicateViewSuffix: () => LocalizedString;
    /**
     * Rename view
     */
    renameView: () => LocalizedString;
    /**
     * View deleted
     */
    viewDeleted: () => LocalizedString;
    /**
     * View renamed
     */
    viewRenamed: () => LocalizedString;
    /**
     * View updated
     */
    viewUpdated: () => LocalizedString;
    /**
     * The last view cannot be deleted.
     */
    lastViewWarning: () => LocalizedString;
    /**
     * Group by
     */
    kanbanGroupBy: () => LocalizedString;
    /**
     * (No value)
     */
    kanbanNoValue: () => LocalizedString;
    /**
     * No select field found. Please create a select field first.
     */
    noSelectFields: () => LocalizedString;
    /**
     * Repeats
     */
    recurrenceLabel: () => LocalizedString;
    /**
     * Does not repeat
     */
    recurrenceNone: () => LocalizedString;
    recurrenceFrequency: {
      /**
       * Daily
       */
      daily: () => LocalizedString;
      /**
       * Weekly
       */
      weekly: () => LocalizedString;
      /**
       * Monthly
       */
      monthly: () => LocalizedString;
      /**
       * Yearly
       */
      yearly: () => LocalizedString;
    };
    /**
     * Every {n} …
     */
    recurrenceInterval: (arg: { n: unknown }) => LocalizedString;
    /**
     * Recurrence saved
     */
    recurrenceSaved: () => LocalizedString;
    /**
     * Search lists…
     */
    searchPlaceholder: () => LocalizedString;
    /**
     * Favorites
     */
    favorites: () => LocalizedString;
    /**
     * No favorites yet. Click the star next to a list.
     */
    noFavorites: () => LocalizedString;
    /**
     * Added to favorites
     */
    favoriteAdded: () => LocalizedString;
    /**
     * Removed from favorites
     */
    favoriteRemoved: () => LocalizedString;
    /**
     * All lists
     */
    allLists: () => LocalizedString;
    /**
     * Drag to reorder
     */
    dragToReorder: () => LocalizedString;
    /**
     * Remove from favorites
     */
    removeFromFavorites: () => LocalizedString;
    /**
     * Add to favorites
     */
    addToFavorites: () => LocalizedString;
    /**
     * Search for a person…
     */
    personSearch: () => LocalizedString;
    /**
     * Search for a person
     */
    personSearchLabel: () => LocalizedString;
    /**
     * Select persons
     */
    personPickerLabel: () => LocalizedString;
    /**
     * Remove {name}
     */
    personRemove: (arg: { name: unknown }) => LocalizedString;
    /**
     * Not in system
     */
    personExternal: () => LocalizedString;
    /**
     * Add "{name}"
     */
    personAddFreeText: (arg: { name: unknown }) => LocalizedString;
  };
  activity: {
    /**
     * Activity
     */
    title: () => LocalizedString;
    /**
     * No recent activity.
     */
    noActivity: () => LocalizedString;
    /**
     * Load more
     */
    loadMore: () => LocalizedString;
  };
  notifications: {
    /**
     * Notifications
     */
    title: () => LocalizedString;
    /**
     * Mark all as read
     */
    markAllRead: () => LocalizedString;
    /**
     * All
     */
    allNotifications: () => LocalizedString;
    /**
     * Unread
     */
    onlyUnread: () => LocalizedString;
    /**
     * No notifications yet.
     */
    noNotifications: () => LocalizedString;
    /**
     * Mark as read
     */
    markRead: () => LocalizedString;
  };
  messaging: {
    /**
     * Messages
     */
    title: () => LocalizedString;
    /**
     * No conversations yet.
     */
    noConversations: () => LocalizedString;
    /**
     * No messages yet.
     */
    noMessages: () => LocalizedString;
    /**
     * Select a conversation to start chatting.
     */
    selectConversation: () => LocalizedString;
    /**
     * Write a message…
     */
    messagePlaceholder: () => LocalizedString;
    /**
     * Send
     */
    send: () => LocalizedString;
    /**
     * New message
     */
    newMessage: () => LocalizedString;
    /**
     * {count} unread
     */
    unread: (arg: { count: number }) => LocalizedString;
  };
  hiveSettings: {
    /**
     * Hive Settings
     */
    title: () => LocalizedString;
    /**
     * General
     */
    generalSection: () => LocalizedString;
    /**
     * Name
     */
    nameLabel: () => LocalizedString;
    /**
     * Your hive name
     */
    namePlaceholder: () => LocalizedString;
    /**
     * Language
     */
    localeLabel: () => LocalizedString;
    /**
     * Settings saved
     */
    saveSuccess: () => LocalizedString;
    /**
     * Failed to save
     */
    saveError: () => LocalizedString;
    /**
     * Danger Zone
     */
    dangerZone: () => LocalizedString;
    /**
     * Permanently deletes the hive and all its data. This action cannot be undone.
     */
    deleteDescription: () => LocalizedString;
    /**
     * Type "DELETE" to confirm
     */
    deleteConfirmLabel: () => LocalizedString;
    /**
     * DELETE
     */
    deleteConfirmPlaceholder: () => LocalizedString;
    /**
     * Delete hive
     */
    deleteButton: () => LocalizedString;
    /**
     * Notifications
     */
    notificationPrefsSection: () => LocalizedString;
    /**
     * Choose which events trigger in-app and email notifications.
     */
    notificationPrefsDescription: () => LocalizedString;
    /**
     * In-App
     */
    notifInApp: () => LocalizedString;
    /**
     * Email
     */
    notifEmail: () => LocalizedString;
    /**
     * Preferences saved
     */
    notifSaved: () => LocalizedString;
    notifTypes: {
      /**
       * New member joined
       */
      member_joined: () => LocalizedString;
      /**
       * Task assigned to me
       */
      task_assigned: () => LocalizedString;
      /**
       * Event reminder
       */
      event_reminder: () => LocalizedString;
    };
  };
};

export type Formatters = {};
