// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'de';

export type Locales = 'de' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * Q​O​O​M​B
     */
    brand: string;
    /**
     * D​e​i​n​ ​H​i​v​e​,​ ​o​r​g​a​n​i​s​i​e​r​t
     */
    tagline: string;
    /**
     * L​a​d​e​n​.​.​.
     */
    loading: string;
    /**
     * S​p​e​i​c​h​e​r​n
     */
    save: string;
    /**
     * S​p​e​i​c​h​e​r​n​.​.​.
     */
    saving: string;
    /**
     * A​b​b​r​e​c​h​e​n
     */
    cancel: string;
    /**
     * H​i​n​z​u​f​ü​g​e​n
     */
    add: string;
    /**
     * E​n​t​f​e​r​n​e​n
     */
    remove: string;
    /**
     * Z​u​r​ü​c​k
     */
    back: string;
    /**
     * D​e​t​a​i​l​s
     */
    details: string;
    /**
     * A​l​l​e​ ​a​n​z​e​i​g​e​n
     */
    showAll: string;
    /**
     * o​d​e​r
     */
    or: string;
  };
  auth: {
    login: {
      /**
       * W​i​l​l​k​o​m​m​e​n​ ​z​u​r​ü​c​k
       */
      title: string;
      /**
       * M​e​l​d​e​ ​d​i​c​h​ ​i​n​ ​d​e​i​n​e​m​ ​H​i​v​e​ ​a​n
       */
      subtitle: string;
      /**
       * E​-​M​a​i​l
       */
      emailLabel: string;
      /**
       * P​a​s​s​w​o​r​t
       */
      passwordLabel: string;
      /**
       * P​a​s​s​w​o​r​t​ ​v​e​r​g​e​s​s​e​n​?
       */
      forgotPassword: string;
      /**
       * A​n​m​e​l​d​e​n
       */
      signIn: string;
      /**
       * N​o​c​h​ ​k​e​i​n​ ​K​o​n​t​o​?
       */
      noAccount: string;
      /**
       * J​e​t​z​t​ ​e​r​s​t​e​l​l​e​n
       */
      createOne: string;
    };
    register: {
      /**
       * E​r​s​t​e​l​l​e​ ​d​e​i​n​e​n​ ​H​i​v​e
       */
      title: string;
      /**
       * E​r​s​t​e​l​l​e​ ​d​e​i​n​e​n​ ​H​i​v​e
       */
      titleLoading: string;
      /**
       * E​i​n​l​a​d​u​n​g​ ​a​n​n​e​h​m​e​n
       */
      titleInvite: string;
      /**
       * R​i​c​h​t​e​ ​d​e​i​n​ ​K​o​n​t​o​ ​e​i​n​,​ ​u​m​ ​d​e​m​ ​H​i​v​e​ ​b​e​i​z​u​t​r​e​t​e​n
       */
      subtitleInvite: string;
      /**
       * O​r​g​a​n​i​s​i​e​r​e​ ​d​e​i​n​e​ ​F​a​m​i​l​i​e​ ​o​d​e​r​ ​d​e​i​n​ ​T​e​a​m
       */
      subtitle: string;
      /**
       * D​e​i​n​ ​N​a​m​e
       */
      nameLabel: string;
      /**
       * E​-​M​a​i​l
       */
      emailLabel: string;
      /**
       * P​a​s​s​w​o​r​t
       */
      passwordLabel: string;
      /**
       * M​i​n​.​ ​8​ ​Z​e​i​c​h​e​n​ ​m​i​t​ ​G​r​o​ß​b​u​c​h​s​t​a​b​e​,​ ​Z​a​h​l​ ​u​n​d​ ​S​o​n​d​e​r​z​e​i​c​h​e​n
       */
      passwordHint: string;
      /**
       * H​i​v​e​-​N​a​m​e
       */
      hiveNameLabel: string;
      /**
       * z​.​B​.​ ​F​a​m​i​l​i​e​ ​M​ü​l​l​e​r
       */
      hiveNamePlaceholder: string;
      /**
       * H​i​v​e​-​T​y​p
       */
      hiveTypeLabel: string;
      /**
       * H​i​v​e​ ​b​e​i​t​r​e​t​e​n
       */
      joinHive: string;
      /**
       * H​i​v​e​ ​e​r​s​t​e​l​l​e​n
       */
      createHive: string;
      /**
       * D​u​ ​h​a​s​t​ ​b​e​r​e​i​t​s​ ​e​i​n​ ​K​o​n​t​o​?
       */
      alreadyHaveAccount: string;
      /**
       * A​n​m​e​l​d​e​n
       */
      signIn: string;
    };
    forgotPassword: {
      /**
       * P​a​s​s​w​o​r​t​ ​v​e​r​g​e​s​s​e​n
       */
      title: string;
      /**
       * G​i​b​ ​d​e​i​n​e​ ​E​-​M​a​i​l​ ​e​i​n​ ​u​n​d​ ​w​i​r​ ​s​e​n​d​e​n​ ​d​i​r​ ​e​i​n​e​n​ ​L​i​n​k​ ​z​u​m​ ​Z​u​r​ü​c​k​s​e​t​z​e​n
       */
      subtitle: string;
      /**
       * E​-​M​a​i​l
       */
      emailLabel: string;
      /**
       * L​i​n​k​ ​s​e​n​d​e​n
       */
      sendResetLink: string;
      /**
       * Z​u​r​ü​c​k​ ​z​u​r​ ​A​n​m​e​l​d​u​n​g
       */
      backToSignIn: string;
      /**
       * E​-​M​a​i​l​ ​p​r​ü​f​e​n
       */
      successTitle: string;
      /**
       * F​a​l​l​s​ ​e​i​n​ ​K​o​n​t​o​ ​m​i​t​ ​d​i​e​s​e​r​ ​A​d​r​e​s​s​e​ ​e​x​i​s​t​i​e​r​t​,​ ​h​a​b​e​n​ ​w​i​r​ ​e​i​n​e​n​ ​L​i​n​k​ ​z​u​m​ ​Z​u​r​ü​c​k​s​e​t​z​e​n​ ​g​e​s​e​n​d​e​t​.​ ​E​r​ ​i​s​t​ ​1​ ​S​t​u​n​d​e​ ​g​ü​l​t​i​g​.
       */
      successSubtitle: string;
    };
    resetPassword: {
      /**
       * P​a​s​s​w​o​r​t​ ​z​u​r​ü​c​k​s​e​t​z​e​n
       */
      title: string;
      /**
       * W​ä​h​l​e​ ​e​i​n​ ​n​e​u​e​s​ ​P​a​s​s​w​o​r​t​ ​f​ü​r​ ​d​e​i​n​ ​K​o​n​t​o
       */
      subtitle: string;
      /**
       * N​e​u​e​s​ ​P​a​s​s​w​o​r​t
       */
      newPasswordLabel: string;
      /**
       * M​i​n​.​ ​8​ ​Z​e​i​c​h​e​n​ ​m​i​t​ ​G​r​o​ß​b​u​c​h​s​t​a​b​e​,​ ​Z​a​h​l​ ​u​n​d​ ​S​o​n​d​e​r​z​e​i​c​h​e​n
       */
      passwordHint: string;
      /**
       * P​a​s​s​w​o​r​t​ ​b​e​s​t​ä​t​i​g​e​n
       */
      confirmPasswordLabel: string;
      /**
       * P​a​s​s​w​ö​r​t​e​r​ ​s​t​i​m​m​e​n​ ​n​i​c​h​t​ ​ü​b​e​r​e​i​n​.
       */
      passwordMismatch: string;
      /**
       * N​e​u​e​s​ ​P​a​s​s​w​o​r​t​ ​s​e​t​z​e​n
       */
      setNewPassword: string;
      /**
       * Z​u​r​ü​c​k​ ​z​u​r​ ​A​n​m​e​l​d​u​n​g
       */
      backToSignIn: string;
    };
    verifyEmail: {
      /**
       * E​-​M​a​i​l​ ​w​i​r​d​ ​v​e​r​i​f​i​z​i​e​r​t​…
       */
      loadingTitle: string;
      /**
       * E​-​M​a​i​l​ ​b​e​s​t​ä​t​i​g​t
       */
      successTitle: string;
      /**
       * D​e​i​n​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​ ​w​u​r​d​e​ ​b​e​s​t​ä​t​i​g​t​.​ ​D​u​ ​k​a​n​n​s​t​ ​j​e​t​z​t​ ​a​l​l​e​ ​F​u​n​k​t​i​o​n​e​n​ ​n​u​t​z​e​n​.
       */
      successSubtitle: string;
      /**
       * Z​u​m​ ​D​a​s​h​b​o​a​r​d
       */
      goToDashboard: string;
      /**
       * V​e​r​i​f​i​z​i​e​r​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
       */
      failedTitle: string;
      /**
       * D​i​e​s​e​r​ ​L​i​n​k​ ​i​s​t​ ​u​n​g​ü​l​t​i​g​ ​o​d​e​r​ ​a​b​g​e​l​a​u​f​e​n​.
       */
      failedSubtitle: string;
      /**
       * Z​u​r​ü​c​k​ ​z​u​r​ ​A​n​m​e​l​d​u​n​g
       */
      backToSignIn: string;
    };
    passKey: {
      /**
       * M​i​t​ ​P​a​s​s​K​e​y​ ​a​n​m​e​l​d​e​n
       */
      signInWithPassKey: string;
      /**
       * P​a​s​s​K​e​y​-​A​u​t​h​e​n​t​i​f​i​z​i​e​r​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
       */
      authFailed: string;
      /**
       * R​e​g​i​s​t​r​i​e​r​u​n​g​ ​f​e​h​l​g​e​s​c​h​l​a​g​e​n
       */
      registrationFailed: string;
      /**
       * P​a​s​s​K​e​y​s
       */
      sectionTitle: string;
      /**
       * P​a​s​s​K​e​y​ ​h​i​n​z​u​f​ü​g​e​n
       */
      addPassKey: string;
      /**
       * G​e​r​ä​t​e​n​a​m​e​ ​(​o​p​t​i​o​n​a​l​)
       */
      deviceNamePlaceholder: string;
      /**
       * P​a​s​s​K​e​y​ ​r​e​g​i​s​t​r​i​e​r​e​n
       */
      registerPassKey: string;
      /**
       * N​o​c​h​ ​k​e​i​n​e​ ​P​a​s​s​K​e​y​s​ ​r​e​g​i​s​t​r​i​e​r​t​.
       */
      noPassKeysYet: string;
      /**
       * P​a​s​s​K​e​y
       */
      defaultName: string;
      /**
       * H​i​n​z​u​g​e​f​ü​g​t
       */
      added: string;
      /**
       * Z​u​l​e​t​z​t​ ​v​e​r​w​e​n​d​e​t
       */
      lastUsed: string;
      /**
       * N​i​e
       */
      never: string;
    };
  };
  layout: {
    emailVerification: {
      /**
       * B​i​t​t​e​ ​b​e​s​t​ä​t​i​g​e​ ​d​e​i​n​e​ ​E​-​M​a​i​l​-​A​d​r​e​s​s​e​,​ ​u​m​ ​a​l​l​e​ ​F​u​n​k​t​i​o​n​e​n​ ​f​r​e​i​z​u​s​c​h​a​l​t​e​n​.
       */
      message: string;
      /**
       * E​-​M​a​i​l​ ​g​e​s​e​n​d​e​t​ ​✓
       */
      sent: string;
      /**
       * E​r​n​e​u​t​ ​s​e​n​d​e​n
       */
      resend: string;
      /**
       * S​c​h​l​i​e​ß​e​n
       */
      dismiss: string;
    };
    hiveSwitcher: {
      /**
       * H​i​v​e​ ​a​u​s​w​ä​h​l​e​n
       */
      selectHive: string;
    };
    userMenu: {
      /**
       * P​r​o​f​i​l
       */
      profile: string;
      /**
       * A​b​m​e​l​d​e​n
       */
      logout: string;
    };
  };
  profile: {
    /**
     * P​r​o​f​i​l
     */
    title: string;
    /**
     * A​n​z​e​i​g​e​n​a​m​e
     */
    displayNameLabel: string;
    /**
     * D​e​i​n​ ​N​a​m​e
     */
    displayNamePlaceholder: string;
    /**
     * E​-​M​a​i​l
     */
    emailLabel: string;
    /**
     * G​e​b​u​r​t​s​t​a​g
     */
    birthdayLabel: string;
    /**
     * P​r​o​f​i​l​ ​g​e​s​p​e​i​c​h​e​r​t​!
     */
    saved: string;
    /**
     * F​e​h​l​e​r​ ​b​e​i​m​ ​S​p​e​i​c​h​e​r​n​.​ ​B​i​t​t​e​ ​e​r​n​e​u​t​ ​v​e​r​s​u​c​h​e​n​.
     */
    saveError: string;
  };
  dashboard: {
    nav: {
      /**
       * Ü​b​e​r​s​i​c​h​t
       */
      overview: string;
      /**
       * K​a​l​e​n​d​e​r
       */
      calendar: string;
      /**
       * A​u​f​g​a​b​e​n
       */
      tasks: string;
      /**
       * M​i​t​g​l​i​e​d​e​r
       */
      members: string;
      /**
       * S​e​i​t​e​n
       */
      pages: string;
      /**
       * E​i​n​s​t​e​l​l​u​n​g​e​n
       */
      settings: string;
    };
    /**
     * {​c​o​u​n​t​}​ ​M​i​t​g​l​i​e​d​e​r
     * @param {number} count
     */
    memberCount: RequiredParams<'count'>;
    /**
     * E​r​s​t​e​l​l​e​n
     */
    create: string;
    /**
     * E​i​n​l​a​d​e​n
     */
    invite: string;
    /**
     * G​u​t​e​n​ ​M​o​r​g​e​n​,​ ​{​n​a​m​e​}​!​ ​�​�
     * @param {string} name
     */
    greeting: RequiredParams<'name'>;
    /**
     * H​e​u​t​e​:​
     */
    todayIntro: string;
    /**
     * A​u​f​g​a​b​e​n
     */
    tasksLabel: string;
    /**
     * o​f​f​e​n
     */
    openLabel: string;
    /**
     * N​ä​c​h​s​t​e​r​ ​T​e​r​m​i​n
     */
    nextEvent: string;
    /**
     * W​e​i​t​e​r​e​ ​T​e​r​m​i​n​e
     */
    moreEvents: string;
    /**
     * {​d​o​n​e​}​ ​v​o​n​ ​{​t​o​t​a​l​}​ ​e​r​l​e​d​i​g​t
     * @param {number} done
     * @param {number} total
     */
    progressText: RequiredParams<'done' | 'total'>;
    /**
     * A​u​f​g​a​b​e​ ​h​i​n​z​u​f​ü​g​e​n
     */
    addTask: string;
    quickAdd: {
      /**
       * S​c​h​n​e​l​l​ ​h​i​n​z​u​f​ü​g​e​n
       */
      title: string;
      /**
       * W​a​s​ ​s​t​e​h​t​ ​a​l​s​ ​n​ä​c​h​s​t​e​s​ ​a​n​?
       */
      placeholder: string;
      /**
       * H​i​n​z​u​f​ü​g​e​n
       */
      button: string;
      /**
       * T​e​r​m​i​n
       */
      event: string;
      /**
       * A​u​f​g​a​b​e
       */
      task: string;
      /**
       * S​e​i​t​e
       */
      page: string;
    };
    roles: {
      /**
       * E​l​t​e​r​n​t​e​i​l
       */
      parent: string;
      /**
       * K​i​n​d
       */
      child: string;
      /**
       * G​a​s​t
       */
      guest: string;
      /**
       * A​d​m​i​n
       */
      orgAdmin: string;
      /**
       * M​a​n​a​g​e​r
       */
      manager: string;
      /**
       * M​i​t​g​l​i​e​d
       */
      member: string;
    };
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * QOOMB
     */
    brand: () => LocalizedString;
    /**
     * Dein Hive, organisiert
     */
    tagline: () => LocalizedString;
    /**
     * Laden...
     */
    loading: () => LocalizedString;
    /**
     * Speichern
     */
    save: () => LocalizedString;
    /**
     * Speichern...
     */
    saving: () => LocalizedString;
    /**
     * Abbrechen
     */
    cancel: () => LocalizedString;
    /**
     * Hinzufügen
     */
    add: () => LocalizedString;
    /**
     * Entfernen
     */
    remove: () => LocalizedString;
    /**
     * Zurück
     */
    back: () => LocalizedString;
    /**
     * Details
     */
    details: () => LocalizedString;
    /**
     * Alle anzeigen
     */
    showAll: () => LocalizedString;
    /**
     * oder
     */
    or: () => LocalizedString;
  };
  auth: {
    login: {
      /**
       * Willkommen zurück
       */
      title: () => LocalizedString;
      /**
       * Melde dich in deinem Hive an
       */
      subtitle: () => LocalizedString;
      /**
       * E-Mail
       */
      emailLabel: () => LocalizedString;
      /**
       * Passwort
       */
      passwordLabel: () => LocalizedString;
      /**
       * Passwort vergessen?
       */
      forgotPassword: () => LocalizedString;
      /**
       * Anmelden
       */
      signIn: () => LocalizedString;
      /**
       * Noch kein Konto?
       */
      noAccount: () => LocalizedString;
      /**
       * Jetzt erstellen
       */
      createOne: () => LocalizedString;
    };
    register: {
      /**
       * Erstelle deinen Hive
       */
      title: () => LocalizedString;
      /**
       * Erstelle deinen Hive
       */
      titleLoading: () => LocalizedString;
      /**
       * Einladung annehmen
       */
      titleInvite: () => LocalizedString;
      /**
       * Richte dein Konto ein, um dem Hive beizutreten
       */
      subtitleInvite: () => LocalizedString;
      /**
       * Organisiere deine Familie oder dein Team
       */
      subtitle: () => LocalizedString;
      /**
       * Dein Name
       */
      nameLabel: () => LocalizedString;
      /**
       * E-Mail
       */
      emailLabel: () => LocalizedString;
      /**
       * Passwort
       */
      passwordLabel: () => LocalizedString;
      /**
       * Min. 8 Zeichen mit Großbuchstabe, Zahl und Sonderzeichen
       */
      passwordHint: () => LocalizedString;
      /**
       * Hive-Name
       */
      hiveNameLabel: () => LocalizedString;
      /**
       * z.B. Familie Müller
       */
      hiveNamePlaceholder: () => LocalizedString;
      /**
       * Hive-Typ
       */
      hiveTypeLabel: () => LocalizedString;
      /**
       * Hive beitreten
       */
      joinHive: () => LocalizedString;
      /**
       * Hive erstellen
       */
      createHive: () => LocalizedString;
      /**
       * Du hast bereits ein Konto?
       */
      alreadyHaveAccount: () => LocalizedString;
      /**
       * Anmelden
       */
      signIn: () => LocalizedString;
    };
    forgotPassword: {
      /**
       * Passwort vergessen
       */
      title: () => LocalizedString;
      /**
       * Gib deine E-Mail ein und wir senden dir einen Link zum Zurücksetzen
       */
      subtitle: () => LocalizedString;
      /**
       * E-Mail
       */
      emailLabel: () => LocalizedString;
      /**
       * Link senden
       */
      sendResetLink: () => LocalizedString;
      /**
       * Zurück zur Anmeldung
       */
      backToSignIn: () => LocalizedString;
      /**
       * E-Mail prüfen
       */
      successTitle: () => LocalizedString;
      /**
       * Falls ein Konto mit dieser Adresse existiert, haben wir einen Link zum Zurücksetzen gesendet. Er ist 1 Stunde gültig.
       */
      successSubtitle: () => LocalizedString;
    };
    resetPassword: {
      /**
       * Passwort zurücksetzen
       */
      title: () => LocalizedString;
      /**
       * Wähle ein neues Passwort für dein Konto
       */
      subtitle: () => LocalizedString;
      /**
       * Neues Passwort
       */
      newPasswordLabel: () => LocalizedString;
      /**
       * Min. 8 Zeichen mit Großbuchstabe, Zahl und Sonderzeichen
       */
      passwordHint: () => LocalizedString;
      /**
       * Passwort bestätigen
       */
      confirmPasswordLabel: () => LocalizedString;
      /**
       * Passwörter stimmen nicht überein.
       */
      passwordMismatch: () => LocalizedString;
      /**
       * Neues Passwort setzen
       */
      setNewPassword: () => LocalizedString;
      /**
       * Zurück zur Anmeldung
       */
      backToSignIn: () => LocalizedString;
    };
    verifyEmail: {
      /**
       * E-Mail wird verifiziert…
       */
      loadingTitle: () => LocalizedString;
      /**
       * E-Mail bestätigt
       */
      successTitle: () => LocalizedString;
      /**
       * Deine E-Mail-Adresse wurde bestätigt. Du kannst jetzt alle Funktionen nutzen.
       */
      successSubtitle: () => LocalizedString;
      /**
       * Zum Dashboard
       */
      goToDashboard: () => LocalizedString;
      /**
       * Verifizierung fehlgeschlagen
       */
      failedTitle: () => LocalizedString;
      /**
       * Dieser Link ist ungültig oder abgelaufen.
       */
      failedSubtitle: () => LocalizedString;
      /**
       * Zurück zur Anmeldung
       */
      backToSignIn: () => LocalizedString;
    };
    passKey: {
      /**
       * Mit PassKey anmelden
       */
      signInWithPassKey: () => LocalizedString;
      /**
       * PassKey-Authentifizierung fehlgeschlagen
       */
      authFailed: () => LocalizedString;
      /**
       * Registrierung fehlgeschlagen
       */
      registrationFailed: () => LocalizedString;
      /**
       * PassKeys
       */
      sectionTitle: () => LocalizedString;
      /**
       * PassKey hinzufügen
       */
      addPassKey: () => LocalizedString;
      /**
       * Gerätename (optional)
       */
      deviceNamePlaceholder: () => LocalizedString;
      /**
       * PassKey registrieren
       */
      registerPassKey: () => LocalizedString;
      /**
       * Noch keine PassKeys registriert.
       */
      noPassKeysYet: () => LocalizedString;
      /**
       * PassKey
       */
      defaultName: () => LocalizedString;
      /**
       * Hinzugefügt
       */
      added: () => LocalizedString;
      /**
       * Zuletzt verwendet
       */
      lastUsed: () => LocalizedString;
      /**
       * Nie
       */
      never: () => LocalizedString;
    };
  };
  layout: {
    emailVerification: {
      /**
       * Bitte bestätige deine E-Mail-Adresse, um alle Funktionen freizuschalten.
       */
      message: () => LocalizedString;
      /**
       * E-Mail gesendet ✓
       */
      sent: () => LocalizedString;
      /**
       * Erneut senden
       */
      resend: () => LocalizedString;
      /**
       * Schließen
       */
      dismiss: () => LocalizedString;
    };
    hiveSwitcher: {
      /**
       * Hive auswählen
       */
      selectHive: () => LocalizedString;
    };
    userMenu: {
      /**
       * Profil
       */
      profile: () => LocalizedString;
      /**
       * Abmelden
       */
      logout: () => LocalizedString;
    };
  };
  profile: {
    /**
     * Profil
     */
    title: () => LocalizedString;
    /**
     * Anzeigename
     */
    displayNameLabel: () => LocalizedString;
    /**
     * Dein Name
     */
    displayNamePlaceholder: () => LocalizedString;
    /**
     * E-Mail
     */
    emailLabel: () => LocalizedString;
    /**
     * Geburtstag
     */
    birthdayLabel: () => LocalizedString;
    /**
     * Profil gespeichert!
     */
    saved: () => LocalizedString;
    /**
     * Fehler beim Speichern. Bitte erneut versuchen.
     */
    saveError: () => LocalizedString;
  };
  dashboard: {
    nav: {
      /**
       * Übersicht
       */
      overview: () => LocalizedString;
      /**
       * Kalender
       */
      calendar: () => LocalizedString;
      /**
       * Aufgaben
       */
      tasks: () => LocalizedString;
      /**
       * Mitglieder
       */
      members: () => LocalizedString;
      /**
       * Seiten
       */
      pages: () => LocalizedString;
      /**
       * Einstellungen
       */
      settings: () => LocalizedString;
    };
    /**
     * {count} Mitglieder
     */
    memberCount: (arg: { count: number }) => LocalizedString;
    /**
     * Erstellen
     */
    create: () => LocalizedString;
    /**
     * Einladen
     */
    invite: () => LocalizedString;
    /**
     * Guten Morgen, {name}! 👋
     */
    greeting: (arg: { name: string }) => LocalizedString;
    /**
     * Heute:
     */
    todayIntro: () => LocalizedString;
    /**
     * Aufgaben
     */
    tasksLabel: () => LocalizedString;
    /**
     * offen
     */
    openLabel: () => LocalizedString;
    /**
     * Nächster Termin
     */
    nextEvent: () => LocalizedString;
    /**
     * Weitere Termine
     */
    moreEvents: () => LocalizedString;
    /**
     * {done} von {total} erledigt
     */
    progressText: (arg: { done: number; total: number }) => LocalizedString;
    /**
     * Aufgabe hinzufügen
     */
    addTask: () => LocalizedString;
    quickAdd: {
      /**
       * Schnell hinzufügen
       */
      title: () => LocalizedString;
      /**
       * Was steht als nächstes an?
       */
      placeholder: () => LocalizedString;
      /**
       * Hinzufügen
       */
      button: () => LocalizedString;
      /**
       * Termin
       */
      event: () => LocalizedString;
      /**
       * Aufgabe
       */
      task: () => LocalizedString;
      /**
       * Seite
       */
      page: () => LocalizedString;
    };
    roles: {
      /**
       * Elternteil
       */
      parent: () => LocalizedString;
      /**
       * Kind
       */
      child: () => LocalizedString;
      /**
       * Gast
       */
      guest: () => LocalizedString;
      /**
       * Admin
       */
      orgAdmin: () => LocalizedString;
      /**
       * Manager
       */
      manager: () => LocalizedString;
      /**
       * Mitglied
       */
      member: () => LocalizedString;
    };
  };
};

export type Formatters = {};
