// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
  RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'de' | 'de-AT' | 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  common: {
    /**
     * Q​O​O​M​B
     */
    brand: string;
    /**
     * Y​o​u​r​ ​h​i​v​e​,​ ​o​r​g​a​n​i​s​e​d
     */
    tagline: string;
    /**
     * L​o​a​d​i​n​g​.​.​.
     */
    loading: string;
    /**
     * S​a​v​e
     */
    save: string;
    /**
     * S​a​v​i​n​g​.​.​.
     */
    saving: string;
    /**
     * C​a​n​c​e​l
     */
    cancel: string;
    /**
     * A​d​d
     */
    add: string;
    /**
     * R​e​m​o​v​e
     */
    remove: string;
    /**
     * B​a​c​k
     */
    back: string;
    /**
     * D​e​t​a​i​l​s
     */
    details: string;
    /**
     * S​h​o​w​ ​a​l​l
     */
    showAll: string;
    /**
     * o​r
     */
    or: string;
    /**
     * E​m​a​i​l
     */
    emailLabel: string;
    /**
     * P​a​s​s​w​o​r​d
     */
    passwordLabel: string;
    /**
     * M​i​n​.​ ​8​ ​c​h​a​r​a​c​t​e​r​s​ ​w​i​t​h​ ​u​p​p​e​r​c​a​s​e​,​ ​n​u​m​b​e​r​ ​a​n​d​ ​s​p​e​c​i​a​l​ ​c​h​a​r​a​c​t​e​r
     */
    passwordHint: string;
    /**
     * C​r​e​a​t​e
     */
    create: string;
    /**
     * I​n​v​i​t​e
     */
    invite: string;
  };
  nav: {
    /**
     * O​v​e​r​v​i​e​w
     */
    overview: string;
    /**
     * C​a​l​e​n​d​a​r
     */
    calendar: string;
    /**
     * T​a​s​k​s
     */
    tasks: string;
    /**
     * M​e​m​b​e​r​s
     */
    members: string;
    /**
     * P​a​g​e​s
     */
    pages: string;
    /**
     * S​e​t​t​i​n​g​s
     */
    settings: string;
  };
  entities: {
    /**
     * E​v​e​n​t
     */
    event: string;
    /**
     * T​a​s​k
     */
    task: string;
    /**
     * P​a​g​e
     */
    page: string;
  };
  roles: {
    /**
     * P​a​r​e​n​t
     */
    parent: string;
    /**
     * C​h​i​l​d
     */
    child: string;
    /**
     * G​u​e​s​t
     */
    guest: string;
    /**
     * A​d​m​i​n
     */
    orgAdmin: string;
    /**
     * M​a​n​a​g​e​r
     */
    manager: string;
    /**
     * M​e​m​b​e​r
     */
    member: string;
  };
  auth: {
    /**
     * S​i​g​n​ ​i​n
     */
    signIn: string;
    /**
     * B​a​c​k​ ​t​o​ ​s​i​g​n​ ​i​n
     */
    backToSignIn: string;
    login: {
      /**
       * W​e​l​c​o​m​e​ ​b​a​c​k
       */
      title: string;
      /**
       * S​i​g​n​ ​i​n​ ​t​o​ ​y​o​u​r​ ​h​i​v​e
       */
      subtitle: string;
      /**
       * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d​?
       */
      forgotPassword: string;
      /**
       * N​o​ ​a​c​c​o​u​n​t​?
       */
      noAccount: string;
      /**
       * C​r​e​a​t​e​ ​o​n​e
       */
      createOne: string;
    };
    register: {
      /**
       * C​r​e​a​t​e​ ​y​o​u​r​ ​h​i​v​e
       */
      title: string;
      /**
       * A​c​c​e​p​t​ ​i​n​v​i​t​a​t​i​o​n
       */
      titleInvite: string;
      /**
       * S​e​t​ ​u​p​ ​y​o​u​r​ ​a​c​c​o​u​n​t​ ​t​o​ ​j​o​i​n​ ​t​h​e​ ​h​i​v​e
       */
      subtitleInvite: string;
      /**
       * S​t​a​r​t​ ​o​r​g​a​n​i​s​i​n​g​ ​y​o​u​r​ ​f​a​m​i​l​y​ ​o​r​ ​t​e​a​m
       */
      subtitle: string;
      /**
       * Y​o​u​r​ ​n​a​m​e
       */
      nameLabel: string;
      /**
       * H​i​v​e​ ​n​a​m​e
       */
      hiveNameLabel: string;
      /**
       * e​.​g​.​ ​D​o​e​ ​F​a​m​i​l​y
       */
      hiveNamePlaceholder: string;
      /**
       * H​i​v​e​ ​t​y​p​e
       */
      hiveTypeLabel: string;
      /**
       * J​o​i​n​ ​h​i​v​e
       */
      joinHive: string;
      /**
       * C​r​e​a​t​e​ ​h​i​v​e
       */
      createHive: string;
      /**
       * A​l​r​e​a​d​y​ ​h​a​v​e​ ​a​n​ ​a​c​c​o​u​n​t​?
       */
      alreadyHaveAccount: string;
    };
    forgotPassword: {
      /**
       * F​o​r​g​o​t​ ​p​a​s​s​w​o​r​d
       */
      title: string;
      /**
       * E​n​t​e​r​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​n​d​ ​w​e​'​l​l​ ​s​e​n​d​ ​y​o​u​ ​a​ ​r​e​s​e​t​ ​l​i​n​k
       */
      subtitle: string;
      /**
       * S​e​n​d​ ​r​e​s​e​t​ ​l​i​n​k
       */
      sendResetLink: string;
      /**
       * C​h​e​c​k​ ​y​o​u​r​ ​e​m​a​i​l
       */
      successTitle: string;
      /**
       * I​f​ ​a​n​ ​a​c​c​o​u​n​t​ ​e​x​i​s​t​s​ ​f​o​r​ ​t​h​a​t​ ​a​d​d​r​e​s​s​,​ ​w​e​ ​s​e​n​t​ ​a​ ​r​e​s​e​t​ ​l​i​n​k​.​ ​I​t​ ​e​x​p​i​r​e​s​ ​i​n​ ​1​ ​h​o​u​r​.
       */
      successSubtitle: string;
    };
    resetPassword: {
      /**
       * R​e​s​e​t​ ​p​a​s​s​w​o​r​d
       */
      title: string;
      /**
       * C​h​o​o​s​e​ ​a​ ​n​e​w​ ​p​a​s​s​w​o​r​d​ ​f​o​r​ ​y​o​u​r​ ​a​c​c​o​u​n​t
       */
      subtitle: string;
      /**
       * N​e​w​ ​p​a​s​s​w​o​r​d
       */
      newPasswordLabel: string;
      /**
       * C​o​n​f​i​r​m​ ​p​a​s​s​w​o​r​d
       */
      confirmPasswordLabel: string;
      /**
       * P​a​s​s​w​o​r​d​s​ ​d​o​ ​n​o​t​ ​m​a​t​c​h​.
       */
      passwordMismatch: string;
      /**
       * S​e​t​ ​n​e​w​ ​p​a​s​s​w​o​r​d
       */
      setNewPassword: string;
    };
    verifyEmail: {
      /**
       * V​e​r​i​f​y​i​n​g​ ​y​o​u​r​ ​e​m​a​i​l​…
       */
      loadingTitle: string;
      /**
       * E​m​a​i​l​ ​v​e​r​i​f​i​e​d
       */
      successTitle: string;
      /**
       * Y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​h​a​s​ ​b​e​e​n​ ​c​o​n​f​i​r​m​e​d​.​ ​Y​o​u​ ​c​a​n​ ​n​o​w​ ​u​s​e​ ​a​l​l​ ​f​e​a​t​u​r​e​s​.
       */
      successSubtitle: string;
      /**
       * G​o​ ​t​o​ ​d​a​s​h​b​o​a​r​d
       */
      goToDashboard: string;
      /**
       * V​e​r​i​f​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
       */
      failedTitle: string;
      /**
       * T​h​i​s​ ​l​i​n​k​ ​i​s​ ​i​n​v​a​l​i​d​ ​o​r​ ​h​a​s​ ​e​x​p​i​r​e​d​.
       */
      failedSubtitle: string;
    };
    passKey: {
      /**
       * S​i​g​n​ ​i​n​ ​w​i​t​h​ ​P​a​s​s​K​e​y
       */
      signInWithPassKey: string;
      /**
       * P​a​s​s​K​e​y​ ​a​u​t​h​e​n​t​i​c​a​t​i​o​n​ ​f​a​i​l​e​d
       */
      authFailed: string;
      /**
       * R​e​g​i​s​t​r​a​t​i​o​n​ ​f​a​i​l​e​d
       */
      registrationFailed: string;
      /**
       * P​a​s​s​K​e​y​s
       */
      sectionTitle: string;
      /**
       * A​d​d​ ​P​a​s​s​K​e​y
       */
      addPassKey: string;
      /**
       * D​e​v​i​c​e​ ​n​a​m​e​ ​(​o​p​t​i​o​n​a​l​)
       */
      deviceNamePlaceholder: string;
      /**
       * R​e​g​i​s​t​e​r​ ​P​a​s​s​K​e​y
       */
      registerPassKey: string;
      /**
       * N​o​ ​P​a​s​s​K​e​y​s​ ​r​e​g​i​s​t​e​r​e​d​ ​y​e​t​.
       */
      noPassKeysYet: string;
      /**
       * P​a​s​s​K​e​y
       */
      defaultName: string;
      /**
       * A​d​d​e​d
       */
      added: string;
      /**
       * L​a​s​t​ ​u​s​e​d
       */
      lastUsed: string;
      /**
       * N​e​v​e​r
       */
      never: string;
    };
  };
  layout: {
    emailVerification: {
      /**
       * P​l​e​a​s​e​ ​v​e​r​i​f​y​ ​y​o​u​r​ ​e​m​a​i​l​ ​a​d​d​r​e​s​s​ ​t​o​ ​u​n​l​o​c​k​ ​a​l​l​ ​f​e​a​t​u​r​e​s​.
       */
      message: string;
      /**
       * E​m​a​i​l​ ​s​e​n​t​ ​✓
       */
      sent: string;
      /**
       * R​e​s​e​n​d
       */
      resend: string;
      /**
       * D​i​s​m​i​s​s
       */
      dismiss: string;
    };
    hiveSwitcher: {
      /**
       * S​e​l​e​c​t​ ​h​i​v​e
       */
      selectHive: string;
    };
    userMenu: {
      /**
       * P​r​o​f​i​l​e
       */
      profile: string;
      /**
       * S​i​g​n​ ​o​u​t
       */
      logout: string;
    };
  };
  profile: {
    /**
     * P​r​o​f​i​l​e
     */
    title: string;
    /**
     * D​i​s​p​l​a​y​ ​n​a​m​e
     */
    displayNameLabel: string;
    /**
     * Y​o​u​r​ ​n​a​m​e
     */
    displayNamePlaceholder: string;
    /**
     * E​m​a​i​l
     */
    emailLabel: string;
    /**
     * R​o​l​e
     */
    roleLabel: string;
    /**
     * B​i​r​t​h​d​a​y
     */
    birthdayLabel: string;
    /**
     * P​r​o​f​i​l​e​ ​s​a​v​e​d​!
     */
    saved: string;
    /**
     * F​a​i​l​e​d​ ​t​o​ ​s​a​v​e​.​ ​P​l​e​a​s​e​ ​t​r​y​ ​a​g​a​i​n​.
     */
    saveError: string;
    language: {
      /**
       * L​a​n​g​u​a​g​e
       */
      title: string;
      /**
       * C​h​o​o​s​e​ ​t​h​e​ ​l​a​n​g​u​a​g​e​ ​f​o​r​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e
       */
      description: string;
      /**
       * L​a​n​g​u​a​g​e​ ​u​p​d​a​t​e​d​!
       */
      saved: string;
      /**
       * F​a​i​l​e​d​ ​t​o​ ​u​p​d​a​t​e​ ​l​a​n​g​u​a​g​e​.
       */
      saveError: string;
      /**
       * D​e​u​t​s​c​h​ ​(​D​e​u​t​s​c​h​l​a​n​d​)
       */
      deDE: string;
      /**
       * D​e​u​t​s​c​h​ ​(​Ö​s​t​e​r​r​e​i​c​h​)
       */
      deAT: string;
      /**
       * E​n​g​l​i​s​h​ ​(​U​S​)
       */
      enUS: string;
    };
    security: {
      /**
       * S​e​c​u​r​i​t​y
       */
      title: string;
      /**
       * M​a​n​a​g​e​ ​y​o​u​r​ ​P​a​s​s​K​e​y​s​ ​a​n​d​ ​l​o​g​i​n​ ​m​e​t​h​o​d​s
       */
      description: string;
    };
  };
  dashboard: {
    /**
     * {​c​o​u​n​t​}​ ​m​e​m​b​e​r​s
     * @param {number} count
     */
    memberCount: RequiredParams<'count'>;
    /**
     * G​o​o​d​ ​m​o​r​n​i​n​g​,​ ​{​n​a​m​e​}​!​ ​�​�
     * @param {string} name
     */
    greeting: RequiredParams<'name'>;
    /**
     * T​o​d​a​y​:​
     */
    todayIntro: string;
    /**
     * o​p​e​n
     */
    openLabel: string;
    /**
     * N​e​x​t​ ​e​v​e​n​t
     */
    nextEvent: string;
    /**
     * M​o​r​e​ ​e​v​e​n​t​s
     */
    moreEvents: string;
    /**
     * {​d​o​n​e​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​c​o​m​p​l​e​t​e​d
     * @param {number} done
     * @param {number} total
     */
    progressText: RequiredParams<'done' | 'total'>;
    /**
     * A​d​d​ ​t​a​s​k
     */
    addTask: string;
    quickAdd: {
      /**
       * Q​u​i​c​k​ ​a​d​d
       */
      title: string;
      /**
       * W​h​a​t​'​s​ ​c​o​m​i​n​g​ ​u​p​ ​n​e​x​t​?
       */
      placeholder: string;
    };
  };
};

export type TranslationFunctions = {
  common: {
    /**
     * QOOMB
     */
    brand: () => LocalizedString;
    /**
     * Your hive, organised
     */
    tagline: () => LocalizedString;
    /**
     * Loading...
     */
    loading: () => LocalizedString;
    /**
     * Save
     */
    save: () => LocalizedString;
    /**
     * Saving...
     */
    saving: () => LocalizedString;
    /**
     * Cancel
     */
    cancel: () => LocalizedString;
    /**
     * Add
     */
    add: () => LocalizedString;
    /**
     * Remove
     */
    remove: () => LocalizedString;
    /**
     * Back
     */
    back: () => LocalizedString;
    /**
     * Details
     */
    details: () => LocalizedString;
    /**
     * Show all
     */
    showAll: () => LocalizedString;
    /**
     * or
     */
    or: () => LocalizedString;
    /**
     * Email
     */
    emailLabel: () => LocalizedString;
    /**
     * Password
     */
    passwordLabel: () => LocalizedString;
    /**
     * Min. 8 characters with uppercase, number and special character
     */
    passwordHint: () => LocalizedString;
    /**
     * Create
     */
    create: () => LocalizedString;
    /**
     * Invite
     */
    invite: () => LocalizedString;
  };
  nav: {
    /**
     * Overview
     */
    overview: () => LocalizedString;
    /**
     * Calendar
     */
    calendar: () => LocalizedString;
    /**
     * Tasks
     */
    tasks: () => LocalizedString;
    /**
     * Members
     */
    members: () => LocalizedString;
    /**
     * Pages
     */
    pages: () => LocalizedString;
    /**
     * Settings
     */
    settings: () => LocalizedString;
  };
  entities: {
    /**
     * Event
     */
    event: () => LocalizedString;
    /**
     * Task
     */
    task: () => LocalizedString;
    /**
     * Page
     */
    page: () => LocalizedString;
  };
  roles: {
    /**
     * Parent
     */
    parent: () => LocalizedString;
    /**
     * Child
     */
    child: () => LocalizedString;
    /**
     * Guest
     */
    guest: () => LocalizedString;
    /**
     * Admin
     */
    orgAdmin: () => LocalizedString;
    /**
     * Manager
     */
    manager: () => LocalizedString;
    /**
     * Member
     */
    member: () => LocalizedString;
  };
  auth: {
    /**
     * Sign in
     */
    signIn: () => LocalizedString;
    /**
     * Back to sign in
     */
    backToSignIn: () => LocalizedString;
    login: {
      /**
       * Welcome back
       */
      title: () => LocalizedString;
      /**
       * Sign in to your hive
       */
      subtitle: () => LocalizedString;
      /**
       * Forgot password?
       */
      forgotPassword: () => LocalizedString;
      /**
       * No account?
       */
      noAccount: () => LocalizedString;
      /**
       * Create one
       */
      createOne: () => LocalizedString;
    };
    register: {
      /**
       * Create your hive
       */
      title: () => LocalizedString;
      /**
       * Accept invitation
       */
      titleInvite: () => LocalizedString;
      /**
       * Set up your account to join the hive
       */
      subtitleInvite: () => LocalizedString;
      /**
       * Start organising your family or team
       */
      subtitle: () => LocalizedString;
      /**
       * Your name
       */
      nameLabel: () => LocalizedString;
      /**
       * Hive name
       */
      hiveNameLabel: () => LocalizedString;
      /**
       * e.g. Doe Family
       */
      hiveNamePlaceholder: () => LocalizedString;
      /**
       * Hive type
       */
      hiveTypeLabel: () => LocalizedString;
      /**
       * Join hive
       */
      joinHive: () => LocalizedString;
      /**
       * Create hive
       */
      createHive: () => LocalizedString;
      /**
       * Already have an account?
       */
      alreadyHaveAccount: () => LocalizedString;
    };
    forgotPassword: {
      /**
       * Forgot password
       */
      title: () => LocalizedString;
      /**
       * Enter your email and we'll send you a reset link
       */
      subtitle: () => LocalizedString;
      /**
       * Send reset link
       */
      sendResetLink: () => LocalizedString;
      /**
       * Check your email
       */
      successTitle: () => LocalizedString;
      /**
       * If an account exists for that address, we sent a reset link. It expires in 1 hour.
       */
      successSubtitle: () => LocalizedString;
    };
    resetPassword: {
      /**
       * Reset password
       */
      title: () => LocalizedString;
      /**
       * Choose a new password for your account
       */
      subtitle: () => LocalizedString;
      /**
       * New password
       */
      newPasswordLabel: () => LocalizedString;
      /**
       * Confirm password
       */
      confirmPasswordLabel: () => LocalizedString;
      /**
       * Passwords do not match.
       */
      passwordMismatch: () => LocalizedString;
      /**
       * Set new password
       */
      setNewPassword: () => LocalizedString;
    };
    verifyEmail: {
      /**
       * Verifying your email…
       */
      loadingTitle: () => LocalizedString;
      /**
       * Email verified
       */
      successTitle: () => LocalizedString;
      /**
       * Your email address has been confirmed. You can now use all features.
       */
      successSubtitle: () => LocalizedString;
      /**
       * Go to dashboard
       */
      goToDashboard: () => LocalizedString;
      /**
       * Verification failed
       */
      failedTitle: () => LocalizedString;
      /**
       * This link is invalid or has expired.
       */
      failedSubtitle: () => LocalizedString;
    };
    passKey: {
      /**
       * Sign in with PassKey
       */
      signInWithPassKey: () => LocalizedString;
      /**
       * PassKey authentication failed
       */
      authFailed: () => LocalizedString;
      /**
       * Registration failed
       */
      registrationFailed: () => LocalizedString;
      /**
       * PassKeys
       */
      sectionTitle: () => LocalizedString;
      /**
       * Add PassKey
       */
      addPassKey: () => LocalizedString;
      /**
       * Device name (optional)
       */
      deviceNamePlaceholder: () => LocalizedString;
      /**
       * Register PassKey
       */
      registerPassKey: () => LocalizedString;
      /**
       * No PassKeys registered yet.
       */
      noPassKeysYet: () => LocalizedString;
      /**
       * PassKey
       */
      defaultName: () => LocalizedString;
      /**
       * Added
       */
      added: () => LocalizedString;
      /**
       * Last used
       */
      lastUsed: () => LocalizedString;
      /**
       * Never
       */
      never: () => LocalizedString;
    };
  };
  layout: {
    emailVerification: {
      /**
       * Please verify your email address to unlock all features.
       */
      message: () => LocalizedString;
      /**
       * Email sent ✓
       */
      sent: () => LocalizedString;
      /**
       * Resend
       */
      resend: () => LocalizedString;
      /**
       * Dismiss
       */
      dismiss: () => LocalizedString;
    };
    hiveSwitcher: {
      /**
       * Select hive
       */
      selectHive: () => LocalizedString;
    };
    userMenu: {
      /**
       * Profile
       */
      profile: () => LocalizedString;
      /**
       * Sign out
       */
      logout: () => LocalizedString;
    };
  };
  profile: {
    /**
     * Profile
     */
    title: () => LocalizedString;
    /**
     * Display name
     */
    displayNameLabel: () => LocalizedString;
    /**
     * Your name
     */
    displayNamePlaceholder: () => LocalizedString;
    /**
     * Email
     */
    emailLabel: () => LocalizedString;
    /**
     * Role
     */
    roleLabel: () => LocalizedString;
    /**
     * Birthday
     */
    birthdayLabel: () => LocalizedString;
    /**
     * Profile saved!
     */
    saved: () => LocalizedString;
    /**
     * Failed to save. Please try again.
     */
    saveError: () => LocalizedString;
    language: {
      /**
       * Language
       */
      title: () => LocalizedString;
      /**
       * Choose the language for the interface
       */
      description: () => LocalizedString;
      /**
       * Language updated!
       */
      saved: () => LocalizedString;
      /**
       * Failed to update language.
       */
      saveError: () => LocalizedString;
      /**
       * Deutsch (Deutschland)
       */
      deDE: () => LocalizedString;
      /**
       * Deutsch (Österreich)
       */
      deAT: () => LocalizedString;
      /**
       * English (US)
       */
      enUS: () => LocalizedString;
    };
    security: {
      /**
       * Security
       */
      title: () => LocalizedString;
      /**
       * Manage your PassKeys and login methods
       */
      description: () => LocalizedString;
    };
  };
  dashboard: {
    /**
     * {count} members
     */
    memberCount: (arg: { count: number }) => LocalizedString;
    /**
     * Good morning, {name}! 👋
     */
    greeting: (arg: { name: string }) => LocalizedString;
    /**
     * Today:
     */
    todayIntro: () => LocalizedString;
    /**
     * open
     */
    openLabel: () => LocalizedString;
    /**
     * Next event
     */
    nextEvent: () => LocalizedString;
    /**
     * More events
     */
    moreEvents: () => LocalizedString;
    /**
     * {done} of {total} completed
     */
    progressText: (arg: { done: number; total: number }) => LocalizedString;
    /**
     * Add task
     */
    addTask: () => LocalizedString;
    quickAdd: {
      /**
       * Quick add
       */
      title: () => LocalizedString;
      /**
       * What's coming up next?
       */
      placeholder: () => LocalizedString;
    };
  };
};

export type Formatters = {};
